### ISSUE TITLE
Allow language code as argument to --main-audio option in transcode-video

### ISSUE THREAD

**Issue by JMoVS** [donmelton/video_transcoding#8] opened 2015-05-10 12:40 UTC
I called thr script with this:

````
transcode-video --output titlesmall.mkv --add-audio language=deu --audio-width all=double --no-auto-burn title01.mkv
````

My file has an audio track 1 with english and a track 4 which is german. According to help, main output is number 1 by default, so shouldn't need to change/specify it as "adding" means additional audio tracks beside the main track. Resulting video only had the german audio track

**Comment by donmelton** [comment] 2015-05-10 13:30
@daDnaK No, this is the intended behavior. If you read the `--help` output again, notice that it says, "default: 1 or first in selected language." With your `--add-audio language=deu` option, you've selected something other than English. This means the main audio track will become will be the first German track.

It was actually extra work to implement it this way. :) Without this feature, the power of adding by language is somewhat limited.

To get the behavior you want, simply add `--main-audio 1` to your command line.

Anyway, this is technically not a bug, so I'm closing this now.

**Comment by daDnaK** [comment] 2015-05-10 13:38
yeah, but "adding" is for me "I have something <the default> and add something to it, that's why I'm confused. The reason speciifcally is that I specify a language to be added, not chosen. But maybe I'm to pedantic with words.

Please tell me what you think and whether you understand my reasoning

**Comment by daDnaK** [comment] 2015-05-10 13:40
long story short: If there'd be an option of "--main-audio language=deu", I'd understand it but right now, I think the prefix of "add" for "language" is (in my mind) misleading.

Nevertheless, aside from these subtelties, thank you very much for the terrific work with all this transcoding stuff. I read somewhere you recommended storing --big files if originals can't be kept but can't find it anymore. Where's that gone?

**Comment by donmelton** [comment] 2015-05-10 13:59
@daDnaK The "README" file has a section toward the bottom titled "Recommended `transcode-video` usage" containing what I think you're looking for. There it says:

> Use the `--big` option if you can't retain your original source rip or you just have plenty of storage space.

**Comment by donmelton** [comment] 2015-05-10 14:47
@daDnaK I really like your idea of a `--main-audio language=CODE` feature. That's really useful.

And if I add that, I will reconsider your (not really) pedantic concern for the semantics of `--add-audio` too.

So, I'm re-opening this so we (and hopefully) other folks can discuss it.

**Comment by JMoVS** [comment] 2015-05-10 18:21
providing an `--main-audio language=CODE` option would also ease mass conversion as it would obliviate the need the first scan the title (if that's the sole reason for scanning) as it would select the language's track(s) automatically.

**Comment by donmelton** [comment] 2015-05-10 18:22
@JMoVS Agreed! That's exactly why I like the idea. Can't believe I didn't think of that.

**Comment by donmelton** [comment] 2016-05-02 16:11
@JMoVS I have this working now but I haven't checked it in yet. Here's what the new help text looks like:

```
    --main-audio TRACK[=NAME]|LANGUAGE[=NAME]
                    select main track by number or first with language code
                      assigning it an optional name
                      (default: first track, i.e. 1)
                      (language code must be ISO 639-2 format, e.g.: `eng`)
                      (default output can be two audio tracks,
                        both surround and stereo, i.e. "width" is `double`)
```

I've also changed the behavior of the `--add-audio` and `--audio-width` options:

```
    --add-audio TRACK[=NAME]|LANGUAGE[,LANGUAGE,...]|all
                    add track selected by number assigning it an optional name
                      or add tracks selected with one or more language codes
                      or add all tracks
                      (language code must be ISO 639-2 format, e.g.: `eng`)
                      (multiple languages are separated by commas)
                      (default output is single AAC audio track,
                        i.e. "width" is `stereo`)
                      (can be used multiple times)
    --audio-width TRACK|main|other|all=double|surround|stereo
                    set audio output "width" for specific track by number
                      or main track or other non-main tracks or all tracks
                      with `double` to allow room for two output tracks
                      with `surround` to allow single surround or stereo track
                      with `stereo` to allow only single stereo track
                      (can be used multiple times)
```

Let me know what you think. I'll probably release this today.

**Comment by donmelton** [comment] 2016-05-02 21:38
@JMoVS OK, version 0.9.0 was just released with this feature. Just `gem update video_transcoding` to get it. Thanks, again!

**Closed by donmelton** 2016-05-02 21:38 UTC
Labels: enhancement
