### ISSUE TITLE
1st (main) audio track is added twice when using `--add-audio all` or `--copy-audio all`

### ISSUE THREAD

**Issue by faithfracture** [donmelton/video_transcoding#63] opened 2016-04-28 16:29 UTC
I'm not sure if this is expected behavior or not, but it seems that the first audio track is always first converted to single width aac audio no matter what unless you specify some other track as the main audio track (with `--main-audio #`).

For example, if I run with the following parameters:
transcode-video --main-audio 1 --add-audio all --copy-audio all --add-subtitle all --burn-subtitle scan --m4v The_Lord_of_the_Rings_The_Two_Towers.mkv --dry-run

I get the following output:
HandBrakeCLI --input=The_Lord_of_the_Rings_The_Two_Towers.mkv --output=The_Lord_of_the_Rings_The_Two_Towers.m4v --markers --encoder=x264 --crop=0:0:0:0 --strict-anamorphic --encoder-level=auto --quality=1 --deinterlace --rate=30 --pfr --audio=1,1,2 --aencoder=av_aac,copy,copy --audio-fallback=ac3 --subtitle=scan,1 --subtitle-forced --subtitle-burned --encopts=vbv-maxrate=2000:vbv-bufsize=1000:crf-max=25:qpmax=34 --encoder-preset=medium --encoder-profile=high

You can see that the `--audio` option is set to `1,1,2`, using the encoder options `av_aac,copy,copy`. This results in the output having a 2.0 stereo audio track as the default main audio track and the 5.1 surround track being the 2nd track.

However, if I set the main audio to a different track: `--main-audio 2`, I get this output instead:
HandBrakeCLI --input=The_Lord_of_the_Rings_The_Two_Towers.mkv --output=The_Lord_of_the_Rings_The_Two_Towers.m4v --markers --encoder=x264 --crop=0:0:0:0 --strict-anamorphic --encoder-level=auto --quality=1 --deinterlace --rate=30 --pfr --audio=2,1 --aencoder=copy,copy --audio-fallback=ac3 --subtitle=scan,1 --subtitle-forced --subtitle-burned --encopts=vbv-maxrate=2000:vbv-bufsize=1000:crf-max=25:qpmax=34 --encoder-preset=medium --encoder-profile=high

Here you can see that it just copies the audio tracks, but this (obviously) results in the 2nd audio track begin the main audio track. In order to get the 5.1 audio track to be the default audio track, I have to make sure that it is the 2nd track in the mkv file before transcoding.

What also seems weird is if I run with `--audio-width all=double`, I once again wind up with audio track 1 being added twice with one version converted to 2.0 stereo and one being copied, and now the 5.1 audio is the 3rd audio track.
transcode-video --main-audio 2 --add-audio all --audio-width all=double --add-subtitle all --burn-subtitle scan --m4v The_Lord_of_the_Rings_The_Two_Towers.mkv --dry-run

HandBrakeCLI --input=The_Lord_of_the_Rings_The_Two_Towers.mkv --output=The_Lord_of_the_Rings_The_Two_Towers.m4v --markers --encoder=x264 --crop=0:0:0:0 --strict-anamorphic --encoder-level=auto --quality=1 --deinterlace --rate=30 --pfr --audio=2,1,1 --aencoder=av_aac,av_aac,copy --subtitle=scan,1 --subtitle-forced --subtitle-burned --encopts=vbv-maxrate=2000:vbv-bufsize=1000:crf-max=25:qpmax=34 --encoder-preset=medium --encoder-profile=high

It doesn't seem that there is any way, short of modifying the original mkv, to get a 5.1 surround audio track to be output as the main, default track.

**Comment by donmelton** [comment] 2016-04-28 21:26
@faithfracture Without access to more information about the audio tracks in your input movie, I'll say this is the expected behavior, i.e. it is by design and not a bug. I should also note that this behavior is explained in the "[Understanding audio](https://github.com/donmelton/video_transcoding#understanding-audio)" section of the "README" document.

In the future, please provide the console output from the following command when filing an issue like this so I can have your audio track layout and channel configuration:

```
transcode-video --scan "/path/to/Movie.mkv"
```

Without that information, I'll assume for now that your input movie has two audio tracks. And that the first audio track is in surround format and the second is stereo. Which means your audio track layout from that scan command probably looks something like this:

```
  + audio tracks:
    + 1, English (AC3) (5.1 ch) (iso639-2: eng), 48000Hz, 384000bps
    + 2, English (AC3) (2.0 ch) (Dolby Surround) (iso639-2: eng), 48000Hz, 192000bps
```

Now, on to the explanation why this is not a bug. First, let me quote from that "Understanding audio" section:

> By default, the main audio track is transcoded in AAC format and, if the original is multi-channel surround sound, in Dolby Digital AC-3 format. Meaning the output can contain two tracks from the same source in different formats. So, main audio output is "wide" enough for "double" tracks.

This means when you select that first track in surround format from your input file as your main audio track, either by not using the `--main-audio` option or explicitly using `--main-audio 1`, then two output audio tracks are created for that single input. One of those tracks is in AAC format and one is in Dolby Digital AC-3 format.

This also means that when you select that second track in stereo format from your input file as your main audio track, by explicitly using `--main-audio 2`, then only one audio track is created, and it's in AAC format.

So, why does the AAC audio track and not the AC-3 surround track always come first as the default track in the output for you? It's because you're using the `--m4v` option to get an iTunes-friendly MP4 file format.

To keep iTunes, Apple TV, iOS devices and QuickTime Player happy, I have to put the AAC track first. Otherwise it's likely the audio wouldn't playback at all. This is the whacky convention that Apple settled on years ago when surround audio was first just a bonus feature in their iTunes Store downloads.

If you don't want the AAC audio first as the default track when you select a surround input track as main audio, then you have two choices. You can either stop using the `--m4v` option or you can use options like `--audio-width all=surround` or `--audio-width 1=surround` (if `1` is your main track).

If you don't use the `--m4v` option then your output will be in Matroska MKV format. This is the default behavior and what I prefer. But be warned that this format is not compatible with iTunes, Apple TV, iOS devices or QuickTime Player.

If you use the  `--audio-width all=surround` or `--audio-width 1=surround` options to force a surround input track to stay a single track in the output, then it's likely your audio won't play on iTunes, Apple TV, iOS devices and QuickTime if you're also using the `--m4v` option.

I hope that helps.

**Closed by donmelton** 2016-04-28 21:26 UTC

**Comment by faithfracture** [comment] 2016-04-28 21:42
Oooh, I see. I did read the `Understanding Audio` section. Several times, in fact, to try to figure out what I was doing wrong. The "by default" is what I assumed I was overriding by saying `--copy-audio all` or `--add-audio all`. I don't recall reading anything stating that the audio was different for the `--m4v` option - just that it's more friendly for iTunes. 

I play all my content via Apple TV using Plex. If I switch to the 5.1 audio, and I have Plex configured to just pass the audio / video straight through if it can, and it plays just fine. (I suppose maybe Plex is seeing that it's streaming to an Apple TV and converting the audio on the fly). Is the issue with iTunes just that it doesn't like having a 5.1 AC3 audio track as the main audio track?

**Comment by donmelton** [comment] 2016-04-28 21:55
@faithfracture I also use Plex. But my playback device is a Roku instead of an Apple TV.

The good news about Plex is that it really doesn't care what container format you're using, It's fine with MKV, MP4 and a half a dozen others.

The bad news is that Plex assumes, no matter what container format you're using, that the first track is the default track. That means when the file is in MP4 format (e.g. your `.m4v` file), you'll get the AAC audio by default.

This is yet another reason why I hate the MP4 format. :)

You might be better off using the Matroska MKV format. MKV files work fine with Plex and Apple TV. This is because Plex separates your audio and video tracks, no matter what format, and reassembles them as MP4 stream segments so the Apple TV is still happy.

**Comment by faithfracture** [comment] 2016-04-28 21:58
Beautiful! I think I'll switch to MKV format from now on. Thankfully, Plex is cool enough to _remember_ which audio track I used last time, so I won't _have_ to go back and re-convert everything I've already done (although, I _do_ still have all the raw formats... so I might do it anyways :P)

**Comment by cameronks** [comment] 2016-04-28 22:31
You should be able to just remux the mp4's as an mkv with no quality loss. That's be much better than re-encoding (if that's what you meant).

**Comment by faithfracture** [comment] 2016-04-28 22:32
Oh yeah! I forgot about the convert-video tool. Thanks 👍

**Comment by donmelton** [comment] 2016-04-29 02:08
@faithfracture Be warned that the `convert-video` tool doesn't handle subtitles tracks. That's a deliberate limitation. However, `convert-video` will correctly swap your first two audio tracks and set the default flag on the new first track.

If you use `mkvmerge` directly, you may be able to move some or all of your subtitle tracks over during remuxing. But you must remember to swap the audio tracks and set the default flag yourself.
