### ISSUE TITLE
HandBrakeCLI Problem

### ISSUE THREAD

**Issue by asheimo** [donmelton/video_transcoding#230] opened 2018-10-30 21:14 UTC
Not sure what I'm missing, I updated to the latest version of transcode video and HandBrakeCLI. 

c:\bin>transcode-video <path to video>
HandBrakeCLI: unknown option -- auto-anamorphic
unknown option (--auto-anamorphic)
C:/Ruby22-x64/bin/transcode-video: transcoding failed: <path to video>

**Comment by khaosx** [comment] 2018-10-30 22:18
Can you run the command from the directory that transcode-video lives in and paste the output back here?

**Comment by asheimo** [comment] 2018-10-31 00:09
C:\Ruby22-x64\bin>transcode-video --quick <path to video>
HandBrakeCLI: unknown option -- auto-anamorphic
unknown option (--auto-anamorphic)
C:/Ruby22-x64/bin/transcode-video: transcoding failed: <path to video>

**Comment by donmelton** [comment] 2018-10-31 00:12
@asheimo Sorry I took so long to respond. I've been away all day.

The problem is that you're using an old version `HandBrakeCLI`. You need to be using version 1.0.0 or later.

You can test which version you have installed by issuing this command:

```
HandBrakeCLI --version
```

What does that output of that command look like?

**Comment by asheimo** [comment] 2018-10-31 00:19
I thought that too but this is the output I get:

c:\bin>HandBrakeCLI.exe --version
[20:15:12] hb_init: starting libhb thread
[20:15:12] thread 5517020 started ("libhb")
HandBrake 1.1.2

**Comment by asheimo** [comment] 2018-10-31 00:28
well embarrassment strikes again... I searched for HandBrakeCLI and found a copy in the C:/Ruby22-x64/bin directory. When I deleted that TranscodeVideo began working as normal.  Please feel free to mark closed and note it was an issue between the keyboard and floor.

**Comment by donmelton** [comment] 2018-10-31 00:31
@asheimo No worries! I'm glad you solved the problem.

I'll close this now but never be shy about opening a issue.

**Closed by donmelton** 2018-10-31 00:31 UTC
Labels: help wanted
