### ISSUE TITLE
Calling script results in "undefined method" error

### ISSUE THREAD

**Issue by daDnaK** [donmelton/video_transcoding#9] opened 2015-05-10 12:44 UTC
I called it with these parameters:
````
transcode-video --main-audio 1=English --add-audio language=deu --audio-width all=double --no-auto-burn /title01.mkv
````

and the output was:
````
/usr/local/bin/transcode-video: undefined method `[]' for nil:NilClass
````

**Comment by daDnaK** [comment] 2015-05-10 12:47
seems to be the "--main-audio" call in this case. Removing that results in no error aside fromm #8

**Comment by donmelton** [comment] 2015-05-10 13:36
@daDnaK Nice catch! Thanks for finding this. I can reproduce it, too. Sorry about that.

I'll start working on a fix after I get back from Mother's Day festivities today.

**Comment by donmelton** [comment] 2015-05-10 16:50
@daDnaK Found the bug. Really stupid. This is what I get for trying to be clever with Ruby. :)

**Comment by daDnaK** [comment] 2015-05-10 16:51
now you can try what happens if you omit the "-m" option when tagging ;-)

**Comment by donmelton** [comment] 2015-05-10 16:53
@daDnaK Nope. :) Seriously, I have a plan for release notes. I just need a little more time.

**Comment by daDnaK** [comment] 2015-05-10 16:58
ah ok, take your time ;-)

**Comment by donmelton** [comment] 2015-05-10 18:05
@daDnaK OK, the fix is in just `gem update` and it should work now. Thanks again!

**Closed by donmelton** 2015-05-10 18:05 UTC

**Comment by JMoVS** [comment] 2015-05-10 18:16
@daDnaK is now @JMoVS, as by your *request* (came around to do that)

**Comment by donmelton** [comment] 2015-05-10 18:17
@JMoVS Wow! Is that a new account? Or can your rename them?

**Comment by JMoVS** [comment] 2015-05-10 18:30
you can rename them, it just won't relink previous mentions and won't redirect the profile page but *will* redirect repository addresses

**Comment by jsonbecker** [comment] 2015-07-06 04:34
I am getting this same issue with the most up-to-date version of the scripts.

```
transcode-video --big --quick --mp4 --main-audio 2 --crop 140:140:0:0 Jupiter\ Ascending\ \(2015\).mkv -o ../movie/Jupiter\ Ascending\ \(2015\)
```
returns
```
/Users/jason/.rvm/gems/ruby-2.2.1/bin/transcode-video: undefined method `[]' for nil:NilClass
```

**Comment by donmelton** [comment] 2015-07-06 05:17
@jsonbecker Then it's probably a different bug. I'll take a look when I'm back home tomorrow.

Question: does the `.."/movie/Jupiter Ascending (2015)"` already exist?

**Comment by jsonbecker** [comment] 2015-07-06 05:43
It does. Thanks for the prompt response.

**Comment by donmelton** [comment] 2015-07-07 21:36
@jsonbecker Sorry this took so long. And also sorry I didn't see the problem right from the beginning.

This is not a bug so much as a side effect of the way Ruby processes command line options.

Your command line will never work as is because you're passing an option after the input argument, i.e. you're doing something like this:

```
transcode-video --mp4 orginal.mkv --output directory/
```

See the problem? The options need to come before the input arguments. Just re-arrange your command like this and it should work fine:

```
transcode-video --big --quick --mp4 --main-audio 2 --crop 140:140:0:0 -o ../movie/Jupiter\ Ascending\ \(2015\) Jupiter\ Ascending\ \(2015\).mkv
```

**Comment by jsonbecker** [comment] 2015-07-07 22:07
That doesn’t seem to do it. If I remove `—main-audio 2` it works fine (ish, I get this error `[truehd @ 0x103801000] major sync info header checksum error` because it can’t decode the first audio track right).

**Comment by donmelton** [comment] 2015-07-07 22:54
@jsonbecker OK, that... doesn't make any sense. Can I see the output of this command?

```
transcode-video --scan Jupiter\ Ascending\ \(2015\).mkv
```

**Comment by jsonbecker** [comment] 2015-07-07 23:41
So this is strange. VLC shows two audio tracks, the first one skips and the second one plays fine. But `transcode-video --scan` clearly shows only one track:

```
+ title 1:
  + stream: Jupiter Ascending (2015).mkv
  + duration: 02:07:34
  + size: 1920x1080, pixel aspect: 1/1, display aspect: 1.78, 23.976 fps
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 00:08:45
    + 2: cells 0->0, 0 blocks, duration 00:10:46
    + 3: cells 0->0, 0 blocks, duration 00:12:02
    + 4: cells 0->0, 0 blocks, duration 00:10:09
    + 5: cells 0->0, 0 blocks, duration 00:07:53
    + 6: cells 0->0, 0 blocks, duration 00:08:54
    + 7: cells 0->0, 0 blocks, duration 00:10:50
    + 8: cells 0->0, 0 blocks, duration 00:09:47
    + 9: cells 0->0, 0 blocks, duration 00:10:02
    + 10: cells 0->0, 0 blocks, duration 00:06:59
    + 11: cells 0->0, 0 blocks, duration 00:07:18
    + 12: cells 0->0, 0 blocks, duration 00:09:32
    + 13: cells 0->0, 0 blocks, duration 00:05:01
    + 14: cells 0->0, 0 blocks, duration 00:09:35
  + audio tracks:
    + 1, English (AC3) (5.1 ch) (Dolby Digital EX) (iso639-2: eng), 48000Hz, 384000bps
  + subtitle tracks:
    + 1, English (iso639-2: eng) (Bitmap)(PGS)
```

**Comment by donmelton** [comment] 2015-07-07 23:43
@jsonbecker I would trust what `HandBrakeCLI` thinks that file contains then. And that explains the other problem you were having.

But it's entirely possible the file is corrupt somehow.
