### ISSUE TITLE
use ffmpeg for detect-crop instead of mplayer

### ISSUE THREAD

**Issue by legrostdg** [donmelton/video_transcoding#120] opened 2017-01-26 18:38 UTC
mplayer is quite a big dependency. If it's used only for crop detection, would it be possible to replace it by ffmpeg?

https://stackoverflow.com/questions/17265381/ffmpeg-get-value-from-cropdetect

**Comment by donmelton** [comment] 2017-01-26 19:00
@legrostdg I have recently considered using `ffmpeg` for crop detection. And my experiments show it would, with a little effort, actually do the job. But...

How do you then preview the crop? I'm afraid you're stuck with `mplayer` for that.

Now, you might suggest `ffplay`for previewing. But most distributions of `ffmpeg` no longer include that tool. And, truth be told, it doesn't work well anyway.

A better idea might be using `mpv` for preview and, possibly, detection too since it includes the "libav" routines required for that. But that would mean complicated scripts written in Lua that don't exactly fit on the command line.

So, I'm afraid we're stuck with `mplayer`. :(

I'm closing this now but feel free to continue commenting. Especially if you figure out a way to solve these problems. Heck, I'll re-open the issue and get to coding it.

**Comment by donmelton** [comment] 2017-01-26 19:02
@legrostdg Seriously, I'm really worried about depending on `mplayer` for the long term since it appears the whole project might be moribund.

If you have experience with Lua and can figure out how to leverage `mpv` for this then I would love to collaborate on the effort.

**Comment by legrostdg** [comment] 2017-01-26 20:10
https://github.com/mpv-player/mpv/wiki/User-Scripts mentions https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua.

Can't you just get the dimensions with ffmpeg and use mpv with these dimensions? Why would you need to have one command calculating the crop and playing a preview?

**Comment by legrostdg** [comment] 2017-01-26 20:18
mpv --vf=crop[=w:h:x:y]

**Comment by donmelton** [comment] 2017-01-26 20:23
@legrostdg Yes, I've perused that Lua script many times in the last few weeks. :)

You're correct that the same tool isn't _required_ to detect the crop. But using two different tools would mean that `crop-detect`itself  would have yet another dependency.

You're also correct that using `--vf=crop` with `mpv` would display the cropped video. But how do you show the bordered version? There's no equivalent `--vf=rectangle` filter. And I don't want to lose that feature since I use it all the time.

**Comment by legrostdg** [comment] 2017-01-26 20:46
I'm sure you can draw a rectangle with ffmpeg, and then play with whatever you want.

https://ffmpeg.org/ffmpeg-filters.html#drawbox

**Comment by donmelton** [comment] 2017-01-26 20:57
@legrostdg How could I draw a rectangle with `ffmpeg` when it's not the player? I would have to transcode the whole video for that.

The problem here is that `mpv` doesn't have the equivalent filter. At least, none that I can find so far.

**Comment by donmelton** [comment] 2017-01-26 21:29
@legrostdg OK, I did some more digging. It seems that `mpv` allows access to the `drawbox`  filter through its `-vf lavfi` option. I'm playing with it now.

So, I'll re-open this for consideration.

**Comment by donmelton** [comment] 2017-01-26 22:18
@legrostdg Here are preview commands for a typical video using `mplayer` :

```
mplayer -really-quiet -nosound -vf rectangle=1920:800:0:140 Movie.mkv
mplayer -really-quiet -nosound -vf crop=1920:800:0:140 Movie.mkv
```

...and the same video using `mpv`:

```
mpv --no-audio --vf lavfi=[drawbox=0:140:1920:800:invert:1] Movie.mkv
mpv --no-audio --vf crop=1920:800:0:140  Movie.mkv
```

As you can see, the `drawbox` coordinates are flipped for `mpv`. But everything works the same.

**Comment by donmelton** [comment] 2017-01-27 02:33
@legrostdg I'm playing with `ffmpeg` now to remind myself of how it works with the `cropdetect` filter. It's very similar to `mplayer`, which is not surprising since they use essentially the same code. :)

So, I can switch over from using `mplayer` for crop detection to using `ffmpeg` as you suggest. The hard part will be 1) parsing the different output, 2) testing it to make sure nothing breaks and 3) making sure it doesn't return radically different results.

But before I do any of that I want to write a proposal detailing _all_ the changes required and ask for feedback. Because this means an added, possibly optional, dependency on `mpv` for previewing the crop results. And people may not actually want that if the system they have already works.

Plus, I need @samhutchins and @JMoVS to weigh in for what this means for the Windows platform since they're the experts there.

I'll probably open a new issue to cover all theses changes and reference your issue here, leaving it open as well.

Thanks for the prod to get me off my ass and moving on this! And let me know what you think.

**Comment by donmelton** [comment] 2017-01-27 02:39
@legrostdg BTW, I could probably figure out a way to use `mpv` now for crop detection but it appears to be _much_ easier to implement with `ffmpeg`, as you suspected. :)

**Comment by donmelton** [comment] 2017-01-27 02:51
@legrostdg Uh oh. Houston, we have a problem. :(

It appears that `ffmpeg` may not work after all. That's because it won't actually seek to a specific offset in the input file using its `-ss` option without scanning through the whole file up until that point. Since my crop detection algorithm for `mplayer` skips through the file to sample it, much like HandBrake does itself, this would be performance disaster to implement.

**Comment by legrostdg** [comment] 2017-01-27 10:20
Maybe using `ffplay` is not so bad after all? On debian, it is installed with `ffmpeg`.

**Comment by legrostdg** [comment] 2017-01-27 10:28
or you can use `ffmpeg -t`

**Comment by samhutchins** [comment] 2017-01-27 10:46
@donmelton Easy enough to install on Windows, same as MPlayer really: download a nightly build and drop it in a folder in $PATH. Like all these projects they link out to 3rd party builders for Windows versions.

Doubt I'll have time to try the Linux Subsystem thing until next week, but maybe @JMoVS will be able to try sooner.

It's possible that mpv will be less finicky than MPlayer on Windows, if you recall I has some issues with MPlayer that I couldn't nail down the source of. The UI for mpv is much nicer too

**Comment by donmelton** [comment] 2017-01-27 17:14
@legrostdg Unfortunately `ffplay` isn't included with the Homebrew-based installation, which is what the majority of folks use.

And, the `-t` option only sets the duration, not the offset within the input file. So that won't work either. :(

**Comment by donmelton** [comment] 2017-01-27 17:16
@samhutchins Cool. Well, since I've hit a snag with using `ffmpeg` to do the crop detection part, this is going to take awhile anyway.

**Comment by legrostdg** [comment] 2017-01-27 17:28
Sure, `-t` sets the duration, but you can combine it with `-ss` to get a offset. `-t 5 -ss 10` to get a 5s extract starting at 10s. If that's what you were asking for...

Can't ffplay be added to the homebrew formula of ffmpeg?

**Comment by donmelton** [comment] 2017-01-27 18:28
@legrostdg Yes, but the problem is `-ss` itself. It has to very slowly scan through the whole file to get to the offset. That just won't ever be performant.

Yes, I believe `ffplay` can be added to the Homebrew install of `ffmpeg`. But it's non-trivial for most users. And it's slow to add it because it requires a complete re-compile of `ffmpeg`. And that last time I required that users hated it.

But there's another reason to avoid `ffplay`. It's not included by default because it's almost as moribund of a project as `mplayer` itself.

**Comment by legrostdg** [comment] 2017-01-27 18:33
OK, I did not get the `-ss` problem. Is that what `-noaccurate_seek` is for?

OK for `ffplay`.

**Comment by donmelton** [comment] 2017-01-27 21:04
@legrostdg The `-noaccurate_seek` option is actually the default behavior so, unfortunately, that doesn't speed anything up.

**Comment by donmelton** [comment] 2017-01-27 21:42
@legrostdg Apparently I'm an idiot. :) I was stupidly placing the `-ss` option after the `-i` option. It has to come before the input file to work correctly. I forgot that `ffmpeg` is mind-numbingly anal-retentive about the order of options and input files.

So, we're back on! I can make this work. I think. :)

**Comment by legrostdg** [comment] 2017-01-28 08:48
> The -noaccurate_seek option is actually the default behavior so, unfortunately, that doesn't speed anything up.

On debian at least the default is -accurate_seek (according to the manpage):

       -ss position (input/output)
           When used as an input option (before "-i"), seeks in this input file to position. Note that in most formats it is
           not possible to seek exactly, so ffmpeg will seek to the closest seek point before position.  When transcoding
           and -accurate_seek is enabled (the default), this extra segment between the seek point and position will be
           decoded and discarded. When doing stream copy or when -noaccurate_seek is used, it will be preserved.

**Comment by donmelton** [comment] 2017-01-28 16:01
@legrostdg I was going by the built-in help which seems to imply the opposite. But it doesn't matter since I don't need to use it now.

**Comment by donmelton** [comment] 2017-01-29 01:04
@legrostdg OK, I've got a version of `detect-crop` using `ffmpeg` instead of `mplayer` now. In fact, the code worked correctly the first time I tried it. :)

The good news is that `ffmpeg` appears to be faster than `mplayer` even without using the `-noaccurate_seek` option.

The bad news is that's getting slightly different results in some cases.

This will take much more testing but I think I'm on the right track.

**Comment by donmelton** [comment] 2017-01-29 01:57
@legrostdg Believe it or not using the `-noaccurate_seek` option with `ffmpeg` gets results much closer to those from `mplayer` and it's even faster. :)

**Comment by donmelton** [comment] 2017-01-29 03:29
@legrostdg It seems that for some media files, `ffmpeg` is actually slower than `mplayer` for crop detection. It's rare but it happens. And I have no idea why. Yet.

**Comment by legrostdg** [comment] 2017-01-29 10:01
In the end, what command do you use? If mplayer only use ffmpeg, another solution would be to look directly into mplayer's code to find out what options are used.

**Comment by donmelton** [comment] 2017-01-29 16:09
@legrostdg I'm using the same parameters for both. I suspect it's just the difference in the version of the underlying libraries. Which also explains the few times when the actual crop detection results have been different. And, so far, those few differences may be a good thing because they seem to be more accurate now with `ffmpeg`.

**Comment by donmelton** [comment] 2017-02-17 05:04
@legrostdg Thanks again for filing this! The change is in. Just `gem update video_transcoding` to get version 0.17.0.

**Closed by donmelton** 2017-02-17 05:04 UTC
Labels: enhancement
