### ISSUE TITLE
detect-crop doesn't work on Lord of rings 3

### ISSUE THREAD

**Issue by JMoVS** [donmelton/video_transcoding#17] opened 2015-05-26 16:43 UTC
I ripped a DVD of Lord of the rings 3 and the mkv file is fine for playback but detect-crop only shows 3 dot-lines. It works in general when I supply another film, but only with this one (I also tried renaming it, but it wasn't the name), it doesn't work.

**Comment by donmelton** [comment] 2015-05-26 17:21
@JMoVS I'm sorry but I don't really understand what the problem is here. From your brief description it sounds as if you're using your transcoded file as input to the `detect-crop` tool. Which makes no sense.

Is `detect-crop` hanging? Does it just not produce any output? I can't diagnosis this without more information.

So, please be very explicit about the steps you're using and provide me sample output from `detect-crop` tool that you think looks wrong.

Thanks.

**Comment by donmelton** [comment] 2015-05-26 17:46
@JMoVS BTW, you can get more diagnostic information from `detect-crop` by using the `--verbose` option. And if you use that option twice, i.e. `--verbose --verbose`, you get debugging output. The shortcut to applying that option twice is `-vv` so, try this:

```
detect-crop -vv "/path/to/video.mkv"
```

**Comment by donmelton** [comment] 2015-05-26 18:14
@JMoVS Based on our out-of-band conversation, it seems like the `mplayer` tool, which is called by `detect-crop`, is somehow stuck scanning your input `.mkv` file. I suspect the file may be corrupt since I've never seen behavior like this before. And, unfortunately, there's not much I can do about that.

Sorry. :(

I'll close this now but feel free to continue adding comments.

**Closed by donmelton** 2015-05-26 18:14 UTC
