### ISSUE TITLE
Not working due to ffmpeg issue

### ISSUE THREAD

**Issue by rementis** [donmelton/video_transcoding#43] opened 2016-02-03 16:17 UTC
root@billiards:/media/media5/Plex/Movies# convert-video movie.mkv
/usr/local/bin/convert-video: ffmpeg version unknown

Ubuntu 14.04

root@billiards:/media/media5/Plex/Movies# ffmpeg -version
ffmpeg version N-75159-g319898b Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
configuration: --disable-asm --enable-libx264 --enable-gpl
libavutil      55.  1.100 / 55.  1.100
libavcodec     57.  1.100 / 57.  1.100
libavformat    57.  0.100 / 57.  0.100
libavdevice    57.  0.100 / 57.  0.100
libavfilter     6.  1.100 /  6.  1.100
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.100 /  2.  0.100
libpostproc    54.  0.100 / 54.  0.100

**Comment by donmelton** [comment] 2016-02-03 16:38
@rementis Apparently the version string output by your `ffmpeg` contains characters which are not numbers. Ugh. Is this `ffmpeg` binary from Ubuntu or did you build it yourself?

**Comment by rementis** [comment] 2016-02-03 17:02
I tried two versions.  One from a ppa I found online, and one I built 
myself.  Both act the same way.

**Comment by donmelton** [comment] 2016-02-03 18:39
@rementis The only way I can fix this is by not checking the version number because "N-75159-g319898b" looks more like a Git UID. :( But that's what I may have to do.

Stay tuned.

**Comment by palitu** [comment] 2016-02-03 23:26
yeah, ultimately you need to find a version that uses the number, you may have to go back a for versions for it to work.

just check the version when you install them, until you find one with a number.

**Comment by donmelton** [comment] 2016-02-04 00:59
@palitu Apparently this is happening for other people on Linux platforms so I'm actually inclined to disable the version check. I had to do that last month for `mp4track`.

@rementis Are you having version check failures with any of the other tool dependencies, like `mplayer`?

**Comment by Lambdafive** [comment] 2016-02-16 22:33
Dectect-crop is giving me a version unknown error with `mplayer`. I'm on Kubuntu and using the version from the repo, which is `MPlayer2 2.0-728-g2c378c7-4`.

**Comment by kford** [comment] 2016-02-26 03:40
I am experiencing the same on Ubuntu Wily

[> $ detect-crop MyFile.mkv                                     
/usr/local/bin/detect-crop: mplayer version unknown](url)

And output of mplayer -version
> $ mplayer -version                                                           
```
> $ mplayer -version

Unknown option on the command line: --version
Error parsing option on the command line: -version
MPlayer2 2.0-728-g2c378c7-4build1 (C) 2000-2012 MPlayer Team
```

**Comment by donmelton** [comment] 2016-02-26 03:44
@Lambdafive and @kford You both appear to be using MPlayer2 and not the original MPlayer. It's not compatible. Those are also ancient builds. Please install the real MPlayer and let me know if that works for you.

**Comment by kford** [comment] 2016-02-26 03:52
It seems that Ubuntu no longer ships mplayer, only mplayer2.  So i added a PPA with the mplayer daily builds and it has the same issue, maybe because of the "svn" in the version string

**Comment by donmelton** [comment] 2016-02-26 03:56
@kford If the version number is actually an SVN tag then, yeah, that will be a problem. Much like the Git tag, I can't ever parse those to determine a real version.

It saddens me, but I think it's time to remove all the version number checks. :(

**Comment by kford** [comment] 2016-02-26 03:59
I don't know how to get mplayer except for the nightly or the repo, both of which seem to have troublesome characters wrt:parsing the version number.  I could build it manually but that is quite involved and if I were to do that on multiple machines, it would become a big nuissance.  What's really odd is that everything was working forever with your shell scripts, and today I installed your ruby gem (this updated project) and the first time I ran detect-crop and transcode-video, it worked.. then I rebooted and it no longer works.  I didn't upgrade my system even.. strange

**Comment by donmelton** [comment] 2016-02-26 04:03
@kford I added more strict version number checking in the Ruby Gem because I was getting so many Twitter mentions and GitHub issues about compatibility problems. Obviously that didn't work so well. :/

I'll have a new version out soon that removes the checks. Stay tuned...

**Comment by kford** [comment] 2016-02-26 04:04
Awesome thanks!   Is it possible for me to disable it locally?

**Comment by donmelton** [comment] 2016-02-26 04:07
@kford Unfortunately, no, unless you modify the Gem directly. Sorry about that!

But I'll start working on the fix tonight.

**Comment by kford** [comment] 2016-02-26 04:10
Fantastic, I'm good to go on your legacy shell scripts again for the time being (transcoding away as we speak).  I have been happily using them for a couple years now so I really don't know much about what I'm missing anyway!

Thanks again

**Comment by donmelton** [comment] 2016-02-26 04:54
@kford Can you paste in the output of `mplayer -version` for that new nightly build you have? Otherwise I may not actually fix this correctly. Thanks.

**Comment by donmelton** [comment] 2016-02-26 05:23
@kford OK, I have a fix that will probably work anyway. For both MPlayer and FFmpeg. Testing it now...

**Comment by donmelton** [comment] 2016-02-26 05:56
@rementis, @Lambdafive and @kford The fix is complete. Just `gem update` to get version 0.5.1.

And @Lambdafive, make sure you install MPlayer and not MPlayer2.

I'm closing this now but feel free to comment, especially if I screwed something up.

**Closed by donmelton** 2016-02-26 05:56 UTC

**Comment by kford** [comment] 2016-02-26 08:16
@donmelton I just saw your question now about the version output.. At this point though let me try your fix and report back.

**Comment by kford** [comment] 2016-02-26 08:53
@donmelton 

I upgraded the gem and tried again, I'm trying with the default mplayer (mplayer 2) that is in the Wily repository.

```
> $ detect-crop --version                                                                                                                                                                                                                                                      
detect-crop 0.5.1
Copyright (c) 2013-2016 Don Melton
```

```
> $ detect-crop aVideo.mkv                                                                                                                                                                                                                                
/usr/local/bin/detect-crop: mplayer version unknown
```

```
> $ mplayer -version                                                                                                                                                                                                                                                           
Unknown option on the command line: --version
Error parsing option on the command line: -version
MPlayer2 2.0-728-g2c378c7-4build1 (C) 2000-2012 MPlayer Team
```

I didn't reinstall the nightly build of mplayer (the one with the "svn" in the version string) since the default one is still having trouble.  Let me know if you'd like me to do that and retest.

**Comment by donmelton** [comment] 2016-02-26 15:38
@kford You'll have to install the nightly build of the real MPlayer since MPlayer2 will never work.

**Comment by kford** [comment] 2016-02-26 19:46
Ok, installed the daily build of mplayer.  here is the version it's reporting (I'm running Ubuntu Wily 15.10)
```
> $ mplayer -version                                                                                                                  
Unknown option on the command line: -version
Error parsing option on the command line: -version
MPlayer SVN-r37552 (C) 2000-2012 MPlayer Team
```
And I can confirm that it no longer hangs up on the version string.. It's either parsing its non-standard format or ignoring it.

```
> $ detect-crop aMovie.mkv                                                                                                            
...

mplayer -really-quiet -nosound -vf rectangle=720:368:0:58 aMovie.mkv
mplayer -really-quiet -nosound -vf crop=720:368:0:58 aMovie.mkv

transcode-video --crop 58:54:0:0 aMovie.mkv
```

You are, by several orders of magnitude, the fastest owner/maintainer I've ever seen when it comes to helping out users with fixes.

Thank you again

**Comment by donmelton** [comment] 2016-02-26 20:06
@kford You are very welcome, sir!

**Comment by Lambdafive** [comment] 2016-02-29 16:56
I've compiled and installed mplayer v1.3.0 and updated the gem to the latest version and hey presto, all works.

Thanks @donmelton great work.

**Comment by donmelton** [comment] 2016-02-29 17:10
@Lambdafive You are very welcome, sir! I'm so glad that it's working for you now. My apologies for taking so long to respond with a fix.
