### ISSUE TITLE
Video-Transcoding 0.2.1 Issue scanning & Transcoding DVD

### ISSUE THREAD

**Issue by eltito51** [donmelton/video_transcoding#11] opened 2015-05-11 01:09 UTC
Mac OSX 10.7.5 / HandBrake svn6897 (2015021301) / Mapro 1.1

When using the transcode command to encode the DVD taking of Pelhan 123 with the following commands:
transcode-video --title 1 --MP4 --big --output /Volumes/TitoDrive/Local_Movies /Volumes/Taking\ of\ Pelham\ 1\ 2\ 3
transcode-video --scan /Volumes/Taking\ of\ Pelham\ 1\ 2\ 3

Getting the following error on the command line:

transcode-video: invalid subtitle track information:   + combing detected, may be interlaced or telecined

First Error message after several BD trancoding

**Comment by donmelton** [comment] 2015-05-11 01:18
@eltito51 Sorry you hit that error. Based on our Twitter conversation it appears you're using an original unencrypted DVD. HandBrake requires decrypted disc images. However, the error message could be a little more helpful.

In order to confirm this diagnosis, can you paste in the output of your scanning command with the `-vv` option added?

    transcode-video -vv --scan /Volumes/Taking\ of\ Pelham\ 1\ 2\ 3

This will give me debugging information. Thanks.

**Comment by donmelton** [comment] 2015-05-13 03:55
@eltito51 Looking at this closer, the problem may not be an unencrypted DVD. Stay tuned while I investigate further...

**Comment by donmelton** [comment] 2015-05-13 04:22
@eltito51 This actually appears to be the same bug as issue #13. Can't believe I didn't realize that earlier. Sorry about that.

I've got a patch working now. I'll probably submit in the next half hour or so.

**Comment by donmelton** [comment] 2015-05-13 04:41
@eltito51 OK, I just push version 0.2.3. Just do a `gem update` and try it out.

Thank you so much for filing this issue!

I'll close this now, but I'll re-open it if you tell me the problem is not fixed.

**Closed by donmelton** 2015-05-13 04:41 UTC
