### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by robbieroof** [donmelton/video_transcoding#278] opened 2019-05-05 12:20 UTC
Mr. Melton,
I have used your scripts previously with great success. I tried today and got the following error:

Traceback (most recent call last):
	2: from /usr/local/bin/transcode-video:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem video_transcoding (>= 0.a) with executable transcode-video (Gem::GemNotFoundException)

I am NOT a programmer AT ALL. I have updated transcode-video as well as updated, through home-brew, all the dependencies I think. Even re-installed ruby to version 2.6.3.
I am on Mojave 10.14.4. Any thoughts on where I am failing??
Thank you very much.

**Comment by donmelton** [comment] 2019-05-05 16:11
@robbieroof I'm so sorry you're having this problem. But thank you for opening your first issue here on GitHub to explain it. I really appreciate that.

Typically such an error message is caused by Ruby or its Gem package management system not being installed or configured correctly. This can happen to anybody, even me, so don't feel bad.

To diagnose the problem better, I'm going to need you to execute some commands in Terminal.app and paste the results back here. It may take a few iterations back and forth but I'm sure we'll narrow it down.

OK, here are the commands:

```
which ruby

ruby --version

which gem

gem environment

gem list

which transcode-video
```

Thanks for your patience and using my scripts!

**Comment by robbieroof** [comment] 2019-05-05 22:36
Don,
Thank you for the reply. It could be “operator error” but I appreciate you taking the time to try to help straighten me out.

Below are the commands:

Last login: Sun May  5 06:52:42 on ttys000
Robbies-MacBook-Pro:~ robbieroof$ which ruby
/usr/bin/ruby
Robbies-MacBook-Pro:~ robbieroof$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
Robbies-MacBook-Pro:~ robbieroof$ which gem
/usr/bin/gem
Robbies-MacBook-Pro:~ robbieroof$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2.3
  - RUBY VERSION: 2.3.7 (2018-03-28 patchlevel 456) [universal.x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/robbieroof/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/robbieroof/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-18
  - GEM PATHS:
     - /Library/Ruby/Gems/2.3.0
     - /Users/robbieroof/.gem/ruby/2.3.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/Wireshark.app/Contents/MacOS
Robbies-MacBook-Pro:~ robbieroof$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
CFPropertyList (2.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3.1)
libxml-ruby (2.9.0)
minitest (5.8.5)
net-telnet (0.1.1)
nokogiri (1.5.6)
power_assert (0.2.6)
psych (2.1.0.1)
rake (10.4.2)
rdoc (4.2.1)
sqlite3 (1.3.11)
test-unit (3.1.5)
Robbies-MacBook-Pro:~ robbieroof$ 
Robbies-MacBook-Pro:~ robbieroof$ which transcode-video
/usr/local/bin/transcode-video
Robbies-MacBook-Pro:~ robbieroof$

**Comment by donmelton** [comment] 2019-05-06 02:07
@robbieroof Sorry I took so long to reply.

This is excellent information and exactly what I needed to diagnose your problem!

It seems that you haven't yet set up your shell `$PATH` variable to find either the version of `ruby` that you installed via Homebrew or your installed Gems.

To do that you need to add the following line to the end of your `.bash_profile` file in your home directory:

```
PATH=/usr/local/opt/ruby/bin:$PATH
```

That should fix the problem. Please let me know if it doesn't or if you need additional help.

**Comment by robbieroof** [comment] 2019-05-06 02:42
Don,
Did that. ( I think I did it correctly) Same error. Ran same commands again…. 
Sorry to be a pain……..
Thoughts??


Last login: Sun May  5 21:34:58 on ttys000
Robbies-MacBook-Pro:~ robbieroof$ which ruby
/usr/local/opt/ruby/bin/ruby
Robbies-MacBook-Pro:~ robbieroof$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
Robbies-MacBook-Pro:~ robbieroof$ which gem
/usr/local/opt/ruby/bin/gem
Robbies-MacBook-Pro:~ robbieroof$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/robbieroof/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/lib/ruby/gems/2.6.0/bin
  - SPEC CACHE DIRECTORY: /Users/robbieroof/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.6.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.6.0
     - /Users/robbieroof/.gem/ruby/2.6.0
     - /usr/local/Cellar/ruby/2.6.3/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/opt/ruby/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/Wireshark.app/Contents/MacOS
Robbies-MacBook-Pro:~ robbieroof$ gem list

*** LOCAL GEMS ***

did_you_mean (1.3.0)
minitest (5.11.3)
net-telnet (0.2.0)
power_assert (1.1.3)
rake (12.3.2)
test-unit (3.2.9)
xmlrpc (0.3.0)
Robbies-MacBook-Pro:~ robbieroof$ which transcode-video
/usr/local/bin/transcode-video
Robbies-MacBook-Pro:~ robbieroof$

**Comment by donmelton** [comment] 2019-05-06 04:41
@robbieroof Not a pain at all, sir! And sorry I took so long to respond but I was watching "Game of Thrones."

OK, your Gem environment now looks correct. What you'll need to do now is reinstall the `video_transcoding` Gem because the files previously installed in `/usr/local/bin` are just stubs pointing to the wrong locations. And as you can see from the output of the `gem list` command, both this time and the last time, the system doesn't think you have the `video_transcoding` Gem installed anyway.

Give that a try and see what happens, I.e. `gem install video_transcoding`.

**Comment by robbieroof** [comment] 2019-05-07 00:14
And Mr. Melton - you have helped me solve my problem. I am very grateful for your help. Following the given commands in Terminal is basically the extent of my experience. Troubleshooting - not so much…….
I really appreciate you taking the time and attention to help me. Very grateful.

Have a great week!!

Robbie Roof

**Comment by donmelton** [comment] 2019-05-07 00:17
@robbieroof You are very welcome, sir! I'm so glad it's working for you now.

I'll close this issue now since it's resolved. But feel free to ask for assistance again!

**Closed by donmelton** 2019-05-07 00:17 UTC
Labels: help wanted
