### ISSUE TITLE
Relinking to Original File in FCPX

### ISSUE THREAD

**Issue by TraiGuzie** [donmelton/video_transcoding#282] opened 2019-06-13 21:47 UTC
I use your great video gem for production backups and remote editing offsite with originals at home.

So I create an FCPX library with the original files and relink a copy of that library to the much smaller video-transcode files to send over the internet to editors. Great for all my cameras files except my new Canon 5D IV when relinking in FCPX.

Best I can tell is the new camera has a 3rd “timecode” stream (Stream 2) that doesn’t get passed by video-transcode but does by Compressor’s h.264 algorithm.

<img width="441" alt="Screen Shot 2019-06-13 at 4 45 56 PM" src="https://user-images.githubusercontent.com/7960719/59469878-0b2ca780-8e04-11e9-9809-b060ebd028c1.png">

**Comment by TraiGuzie** [comment] 2019-06-13 21:55
I have uploaded some test files if you need them, separated into Good and Bad folders for the ones that relink vs the ones that don't:


http://www.barnoneweddings.com/films/test.zip

**Comment by donmelton** [comment] 2019-06-13 22:42
@TraiGuzie Thanks for opening the issue and uploading the test files.

Yes, the problem is the third stream which appears to be timecode data. `HandBrakeCLI` can't transcode or even copy that stream since it's not video, audio or a subtitle. So it will always be ignored.

Compressor.app is likely just copying the stream since it has nothing to do with H.264.

Other than removing the stream in your original, I honestly don't know what you can do about this.

**Comment by TraiGuzie** [comment] 2019-06-14 03:53
Interesting. I wonder if there is a way to quickly batch strip that third stream, or perhaps batch add a dummy stream.

Thanks for looking at it Don. Love the tool!

**Comment by donmelton** [comment] 2019-06-14 15:08
@TraiGuzie I just realized that you could try the MP4Box tool to remove those third streams. See:

https://gpac.wp.imt.fr/mp4box/

I believe that's installable via Homebrew. But I'm not sure if it has a batch mode.

**Comment by donmelton** [comment] 2019-06-30 15:53
@TraiGuzie I'll close this for now since we've resolved the issue. But feel free to comment again here or open a new issue if you have more questions.

**Closed by donmelton** 2019-06-30 15:53 UTC
Labels: help wanted
