### ISSUE TITLE
Subtitles - All of track burnt, not only forced

### ISSUE THREAD

**Issue by craig85311** [donmelton/video_transcoding#237] opened 2018-12-19 13:34 UTC
In Red Sparrow, there's Russian spoken at 1:35:54. The main track on subtitle track 1 is English, on the forced is the brief Russian dialog. The English is in gray lettering, while the Russian is in a white. I cannot seem to separate the forced part of the track to burn. Either all or nothing.

**Comment by khaosx** [comment] 2018-12-19 14:05
@craig85311 

Howdy - at first glance, this sounds like an issue with the source media. Can you tell me a little more about how you created the source? Or, even better, a mediainfo dump of the source. 

I'm looking at my encode of Red Sparrow right now, and there are two distinct tracks - one forced and one full. I used makemkv to create my source and it extracted both subtitle tracks correctly, and added the correct mkvflags, so it's likely that the problem is in the process (that's good news, as it's easier to troubleshoot!)

**Comment by donmelton** [comment] 2018-12-19 15:52
@craig85311 Thanks for filing this after our Twitter conversation!

And thanks, @khaosx, for your help as well! Especially since I don't have a copy of "Red Sparrow."

OK, @craig85311, can you include the MediaInfo information about your original source movie and the `.log` file from your transcoding of it? You can attach those as separate files if they're too large to paste in here.

Thanks!

**Comment by craig85311** [comment] 2018-12-20 03:33
I used MakeMKV to rip BD, have 7.1 & 5.1 Dolby tracks, and 4 English subtitle tracks. I unfortunately deleted the .log file. I'll re-transcode. What option should I use for subtitle? I had been using –burn-subtitle 1 (track is 1) for the previous transcode.

**Comment by donmelton** [comment] 2018-12-20 03:58
@craig85311 Isn't the first track the wrong one? I would try `--burn-subtitle 2` this time.

**Comment by khaosx** [comment] 2018-12-20 04:56
Steps to make sure subtitles burn correctly, every time:

1. Look up the title [on this spreadsheet](https://docs.google.com/spreadsheets/d/1nAMVVnmk3vSaUiuFXcN7D0R69FHIP4tfIkTdThTkXEk/edit#gid=20))

2. Select the corresponding tracks in MakeMKV. According to the spreadsheet, you're looking for  separate, non-forced sub track 3. Select it, and then set the mkv flags for that track to DF in MakeMKV.

3. Rip

4. Add this to your command line for transcode-video: --add-subtitle all --no-auto-burn --force-subtitle scan". If you want it burned, then change it to: --burn-subtitle scan.

This will work, so long as you make sure that MakeMKV sets the f (forced) flag on the track that should forced.

**Comment by craig85311** [comment] 2018-12-20 15:47
Ugh I went back to re-play the video with subtitle tracks and it appears to be my fault. I had seen it on what I thought was subtitle track 1 when it was actually playing on subtitle track 3. I'm sorry to waste everyone's time. The script is working as it should, now if I could only do the same! Thanks for your help guys, Happy Holidays :)

**Comment by donmelton** [comment] 2018-12-20 16:07
@craig85311 No problem! I'm just glad the problem was solved. Don't be shy about filing other issues in the future when you get stuck. That's why we're here.

And thanks to @khaosx for jumping in with all the help! I really appreciate all the folks who contribute to our project.

I'll close this now but feel free to keep commenting.

**Closed by donmelton** 2018-12-20 16:07 UTC
Labels: help wanted
