### ISSUE TITLE
ProRes File Error

### ISSUE THREAD

**Issue by blackoctopus** [donmelton/video_transcoding#15] opened 2015-05-14 21:51 UTC
``` 
philips-Mac-Pro:Desktop philipmozolak$ transcode-video --dry-run -vv /Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov
transcode-video 0.2.3
Copyright (c) 2013-2015 Don Melton
Processing: /Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov...
Scanning media title 1 with HandBrakeCLI...
HandBrake 0.10.0 found...
[17:49:42] hb_init: starting libhb thread
HandBrake 0.10.0 (2014112200) - Darwin x86_64 - https://handbrake.fr
8 CPUs detected
Opening /Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov...
[17:49:42] CPU: Intel(R) Xeon(R) CPU           X5482  @ 3.20GHz
[17:49:42]  - logical processor count: 8
[17:49:42] OpenCL device #1: NVIDIA GeForce 8800 GT
[17:49:42]  - OpenCL version: 1.0 
[17:49:42]  - driver version: 10.0.31 310.90.10.05b12
[17:49:42]  - device type:    GPU
[17:49:42]  - supported:      no
[17:49:42] hb_scan: path=/Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov, title_index=1
libbluray/bdnav/index_parse.c:162: indx_parse(): error opening /Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov/BDMV/index.bdmv
libbluray/bdnav/index_parse.c:162: indx_parse(): error opening /Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov/BDMV/BACKUP/index.bdmv
libbluray/bluray.c:2182: nav_get_title_list(/Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov) failed
[17:49:42] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[17:49:42] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2015-05-14 21:19:06
    date            : 2015-05-14T12:45:04-0500
    encoder         : Mac OS X 10.10.4 (14E17e)
  Duration: 00:00:12.01, start: 0.000000, bitrate: 118195 kb/s
    Stream #0.0(eng): Video: prores, yuv422p10le, 1440x1080, 116646 kb/s, PAR 4:3 DAR 16:9, 29.97 fps, 30k tbn (default)
    Metadata:
      creation_time   : 2015-05-14 21:19:06
    Stream #0.1(eng): Data: tmcd / 0x64636D74, 0 kb/s (default)
    Metadata:
      creation_time   : 2015-05-14 21:19:13
    Stream #0.2(eng): Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2015-05-14 21:19:13
[17:49:42] scan: decoding previews for title 1
Scanning title 1 of 1, preview 1, 50.00 %[17:49:43] scan: 2 previews, 1440x1080, 29.970 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 4:3
[17:49:43] scan: removing audio 0x2 because no bitrate found
[17:49:43] libhb: scan thread found 1 valid title(s)
+ title 1:
  + stream: /Users/philipmozolak/Desktop/2015-05-14-River/kD-30117_01.mov
  + duration: 00:00:12
  + size: 1440x1080, pixel aspect: 4/3, display aspect: 1.78, 29.970 fps
  + autocrop: 0/0/0/0
  + support opencl: no
  + support hwd: not built-in
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 00:00:12
  + audio tracks:
  + subtitle tracks:
HandBrake has exited.

/usr/bin/transcode-video: undefined method `[]=' for nil:NilClass
philips-Mac-Pro:Desktop philipmozolak$  
```

**Comment by blackoctopus** [comment] 2015-05-14 21:59
There we go

**Comment by donmelton** [comment] 2015-05-14 21:59
@blackoctopus Thanks!

**Comment by donmelton** [comment] 2015-05-14 22:03
@blackoctopus OK, I can't see anything particularly odd about this other than it doesn't have audio. But I assume all the other ProRes inputs that successfully transcoded also did not have audio?

**Comment by donmelton** [comment] 2015-05-14 22:22
@blackoctopus Now I see something odd. :) The console spew from libavcodec (the FFmpeg-based library used by `HandBrakeCLI`) shows this:

```
    Stream #0.2(eng): Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s (default)
```

Which is clearly an audio track. The third media track in the file.

But when `HandBrakeCLI` parses the track information, it doesn't list that audio track:

```
  + audio tracks:
  + subtitle tracks:
```

Perhaps that second media track is what is confusing everything. I've never seen anything like it:

```
    Stream #0.1(eng): Data: tmcd / 0x64636D74, 0 kb/s (default)
```

What the hell is "tmcd" data?

OK, can you paste in the (properly formatted) output of the same command on a ProRes input file that actually transcodes?

**Comment by donmelton** [comment] 2015-05-14 22:38
@blackoctopus Just to make sure I didn't introduce a regression recently, I just tried transcoding input files with only video tracks. Worked just fine. So we can eliminate that as a possible bug.

**Comment by donmelton** [comment] 2015-05-14 22:43
@blackoctopus Looks like that weird "tmcd" data track is timecode information. Do your other ProRes files have that?

**Comment by donmelton** [comment] 2015-05-14 22:46
@blackoctopus Missed this console spew from `HandBrakeCLI` earlier:

```
[17:49:43] scan: removing audio 0x2 because no bitrate found
```

So that explains the missing audio track. Probably has nothing to do with the timecode then. But the error is hard to believe since libavcodec has already figured out that track is `1536 kb/s`.

**Comment by donmelton** [comment] 2015-05-14 23:36
@blackoctopus I see a possible bug in `media.rb` because `HandBrakeCLI` "removes" that audio track. And that bug could explain the error you're seeing. Now to try working up a patch...

**Comment by donmelton** [comment] 2015-05-15 01:09
@blackoctopus OK, the patch seems to not break anything and potentially fix the `undefined method` error you were seeing. But I don't have your input file so I can't really test that positive case.

And there's still the question of why `HandBrakeCLI` thinks it needs to "remove" the audio track in your "kD-30117_01.mov" file. There's really something screwy about it.

I'll sit on this patch until I get from you what I requested earlier, the (properly formatted) output of the same command on a ProRes input file that actually transcodes. With that, I might be able to at least conclude that it's worth checking in this patch and re-releasing so you can test it.

I'll be offline and away from keyboard for several hours. But I'll check back here tonight if I'm sober enough to deal with it. :) And if not, in the morning.

**Comment by blackoctopus** [comment] 2015-05-15 14:54
Would you like the kD-30117_01.mov file?

**Comment by donmelton** [comment] 2015-05-15 15:03
@blackoctopus As long as it doesn't violate copyright law, sure. :) How would you provide it? Over Dropbox?

**Comment by donmelton** [comment] 2015-05-15 17:55
@blackoctopus It's a good thing you sent me that file! While it now gets past the first `HandBrakeCLI` error with my patch, it's now failing on `mp4track` like this:

```
ReadAtom: "/Users/don/Downloads/kD-30117_01.mov": invalid atom size, extends outside parent atom - skipping to end of "meta" "" 1928879507 vs 177469963
```

That is one damn peculiar movie.

So, I still have work to do. Which is a pity since I was planning to spend the afternoon watching "Daredevil." :)

But, seriously, I'll take a look at this in detail after lunch.

**Comment by donmelton** [comment] 2015-05-15 22:59
@blackoctopus Finally got a chance to look at the problem a few minutes ago. And I already have a patch. That may be some kind of record. :)

Basically the fix for `mp4track` is the same for `HandBrakeCLI`. Boring, really. :) It's just a validity check to make sure a hash item, in this case the track index, actually exists when being re-enumerated. Which is necessary for your "kD-30117_01.mov" file because `HandBrakeCLI` "removes" the audio track after its first pass through it. And I foolishly didn't think that would ever happen.

So, four "if" statements later, the file is transcoding just fine. BTW, that's one plain looking bridge. And who shook the camera halfway through? :)

Now I get to run this through my informal test suite to make sure I didn't break anything with the fix. I'll probably check it in tonight after dinner and then re-release the Gem.

Thanks so much for finding this bug!

**Comment by donmelton** [comment] 2015-05-16 00:08
@blackoctopus OK, the fix is in. Just do a `gem update` and let me know how it goes.

Thanks again!

**Closed by donmelton** 2015-05-16 00:08 UTC
