### ISSUE TITLE
PCM Audio not being recognized, any tips?

### ISSUE THREAD

**Issue by DRAKOZ** [donmelton/video_transcoding#177] opened 2017-11-17 20:38 UTC
Stream #0:1(eng): Audio: pcm_s24le, 48000 Hz, 1 channels, s32 (24 bit), 1152 kb/s (default)
    Metadata:
      title           : Mono
      BPS-eng         : 1152000
      DURATION-eng    : 01:39:26.130000000
      NUMBER_OF_FRAMES-eng: 178984
      NUMBER_OF_BYTES-eng: 859122720
      SOURCE_ID-eng   : 001100
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.10.7 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-11-17 06:23:59
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID

> scan: 10 previews, 1920x1080, 23.976 fps, autocrop = 0/0/220/220, aspect 16:9, PAR 1:1
[10:36:23] scan: removing audio 0x1 because no bitrate found

**Comment by donmelton** [comment] 2017-11-17 20:41
@DRAKOZ Interesting. What version of of `HandBrakeCLI` are you using? Also, does the GUI app recognize the audio tracks?

**Comment by DRAKOZ** [comment] 2017-11-17 21:05
1.0.7+ds1-2build1

And VLC Recognizing it as Mono [English] when opened before transcoding, after there is no track.

**Comment by DRAKOZ** [comment] 2017-11-17 21:06
Also, this is the first error I have encountered using it over 150 times, your transcoding is a lifesaver!! So thank you very much.

**Comment by donmelton** [comment] 2017-11-17 21:11
@DRAKOZ You are very welcome!

OK, I'm not sure what `1.0.7+ds1-2build1` means. Is this a nightly or development build?

Are you saying that after VLC opens the problem file, the track disappears? I don't understand what you mean.

Were you able to try the problem file in the HandBrake application? Also, which platform are you on?

Thanks.

**Comment by DRAKOZ** [comment] 2017-11-17 21:16
Sorry, that's just what Ubuntu spat back as my version. Looks to be the 1.0.7 build for artful aardvark. 

VLC opens and can play the 21gb MKV with the audio track, after using your transcode-video to make it smaller, the audio track is deleted and VLC no longer sees an audio track. 

Pre-trancode: 21gb, audio there
Post-transcode: 4.5gb, no audio

I'm on Ubuntu 17.10

**Comment by donmelton** [comment] 2017-11-17 22:42
@DRAKOZ Ah. OK, that makes sense. Thanks!

It looks like the error you're getting is from `HandBrakeCLI` itself. And I have no idea why it would dislike that particular audio track so much. It's very weird.

That's why I asked if it's possible for you to run the HandBrake GUI application to see if it has the same problem. Is that possibly on Linux?

**Comment by DRAKOZ** [comment] 2017-11-18 01:09
Embarrassingly enough, I've never used the GUI version of handbrake, your code is just so simple to use. I'll give that a go. Thank you!

**Comment by donmelton** [comment] 2017-11-18 01:25
@DRAKOZ Thanks. I'm sure you don't want to do your actual transcoding with the app because it doesn't have my special ratecontrol system, but we can find out if HandBrake fails to recognize the audio track there, too. If it also fails, then we know the problem is definitely with HandBrake.

**Comment by DRAKOZ** [comment] 2017-11-18 03:33
Exactly why I don't use the base GUI.

Wow that took forever. Ok, just used Handbrake with GUI. It is the issue! Totally disregarded the PCM mono audio.

**Comment by donmelton** [comment] 2017-11-18 03:36
@DRAKOZ Thanks for doing that test! Yeah, I suspected it was HandBrake based on the error text that you so nicely pasted into the issue.

Unfortunately, I have no freakin' idea how to fix this problem for you.

Is it possibly that you could remux the file with a utility like `mkvmerge` or `mp4box`? Maybe it's just the container, i.e. the file format itself, that's confusing HandBrake?

**Comment by DRAKOZ** [comment] 2017-11-18 03:40
Great ideas. I'll do some tests and let you know what it turns up. Thank you so much for responding!

**Comment by donmelton** [comment] 2017-11-18 03:45
@DRAKOZ Sure! I'll close this now, but please feel free to comment here (I get the notifications) or re-open if you think there really is a bug in `transcode-video`. Of, heck, just open another issue, too. I'm easy. :)

**Closed by donmelton** 2017-11-18 03:45 UTC
Labels: help wanted
