### ISSUE TITLE
The --strict-anamorphic option was removed from HandBrakeCLI nightly builds on October 31, 2016

### ISSUE THREAD

**Issue by iokui** [donmelton/video_transcoding#96] opened 2016-11-05 21:17 UTC
As of a few days ago, HandbrakeCLI no longer supports strict-anamorphic. 

Output when trying to convert a file:

```
unknown option (--strict-anamorphic)
```

The relevant change to HandbrakeCLI is here:

https://github.com/HandBrake/HandBrake/commit/00eeae7591023ed47a5cd6b90bf7b11ac1bfae41

**Comment by donmelton** [comment] 2016-11-05 23:15
@iokui Yikes! Thanks for the heads up.

Now I need to figure out how to deal with HandBrake versioning schemes again. Oh joy.

**Comment by donmelton** [comment] 2016-11-06 04:34
@iokui You know, I always have a window open to the [HandBrake commits page] (https://github.com/HandBrake/HandBrake/commits/master) and I still missed this when it landed on Halloween. Trick or treat! At least you were paying attention. :)

Or did you get that error using a nightly build?

Anyway, the versioning scheme for `HandBrakeCLI` nightly builds is still a disaster so I'll have to do a hack to determine whether the feature change has been made. Believe it or not, I'll have to parse the output of the `--help` command. I guess it could be worse.

But the hard part of all this making sure the new `--auto-anamorphic` works like the removed `--strict-anamorphic` did. And there's the new `--non-anamorphic` option to consider.

So, lots of testing for me. But I should have a fix soon and maybe even a release next week.

**Comment by iokui** [comment] 2016-11-06 16:07
I did get that error using a nightly build. I've since reverted back to an older nightly build, so transcoding is once again working for my setup. 

I'll wait to use any newer HandBrake builds until I see a fix in your transcode setup.

Thanks for the hard work and testing this transcoding stuff, in my case so that my son can watch a story of a fish who loses his father and gets stuck in a Dentist's office in Australia, and not have to worry about waiting through ancient mandatory trailers or losing the disc under the couch.

**Comment by donmelton** [comment] 2016-11-06 16:13
@iokui Thanks. And I just confirmed that with `HandBrakeCLI-20161102202240-febff04` mere seconds before I received your message. :)

Hopefully I can deliver an updated release soon so you don't have to backtrack again.

And that's darn good movie. Even with a quality transcoding, don't loose your original disc under the couch. :)

**Comment by donmelton** [comment] 2016-11-06 16:32
@iokui Well, the good news is that the new `--auto-anamorphic` option behaves for my purposes just like the old `--strict-anamorphic` option did. Which should make part of the code change much simpler.

**Comment by donmelton** [comment] 2016-11-06 20:34
@iokui OK, I have a patch now which fixes this. And so far it doesn't seem to break anything else when moving back and forth between various versions of `HandBrakeCLI`. I'll need to do some more testing and I might just squeeze in another unrelated minor bug/behavior fix, but it looks like I'll be able to release this today or tomorrow.

**Comment by donmelton** [comment] 2016-11-06 22:08
@iokui OK, I just released version 0.12.2 with the fix. Just `gem update video_transcoding` to get it.

Thanks again for opening this issue!

**Closed by donmelton** 2016-11-06 22:08 UTC
Labels: bug
