### ISSUE TITLE
Naming chapters not working

### ISSUE THREAD

**Issue by martinpickett** [donmelton/video_transcoding#97] opened 2016-11-12 20:17 UTC
I've recently updated to version 12.2 and my transcodes no longer include chapter names from a *.csv file. Is this a known issue?

I've attached example log file and chapters file (note; i've had to change the extension to upload here).

[Doctor Who (2005) - s00e09 - The Next Doctor.chapters.csv.txt](https://github.com/donmelton/video_transcoding/files/587411/Doctor.Who.2005.-.s00e09.-.The.Next.Doctor.chapters.csv.txt)
[Doctor Who (2005) - s00e09 - The Next Doctor.m4v.log.txt](https://github.com/donmelton/video_transcoding/files/587410/Doctor.Who.2005.-.s00e09.-.The.Next.Doctor.m4v.log.txt)

**Comment by donmelton** [comment] 2016-11-12 23:39
@martinpickett Sorry I took so long to respond. I've been AFK most of the afternoon.

Which version of `HandBrakeCLI` are you using? Chapter naming appears to be still broken with nightly builds.

**Comment by martinpickett** [comment] 2016-11-13 00:10
I'm using 0.10.5 which I believe is the latest version.

The only thing I've knowingly changed is updating to version 12.2 of your script.

**Comment by donmelton** [comment] 2016-11-13 00:50
@martinpickett Yeah, 0.10.5 is the official release of HandBrake. I'll take a look at this later tonight and see if I can reproduce the problem.

**Comment by kvanh** [comment] 2016-11-13 02:51
I used --dry-run option and I can see the --markers= is passed correctly. I was seeing this with an older HandBrakeCLI (forget which date) but just tried the HandBrakeCLI-20161111192113-167cc7a-master-osx and still broken.  CSV file attached.

[Chronicles of Riddick.chapters.csv.txt](https://github.com/donmelton/video_transcoding/files/587561/Chronicles.of.Riddick.chapters.csv.txt)

**Comment by donmelton** [comment] 2016-11-13 02:57
@kvanh Thanks! This is what I suspect the problem is.

**Comment by kvanh** [comment] 2016-11-13 03:55
10.5 HandBrakeCLI appears to be working for me. just started re-running previous test and i can see the chapter names as it transcodes them.

**Comment by donmelton** [comment] 2016-11-13 03:57
@martinpickett @kvanh I just tried `transcode-video` version 0.12.2 with `HandBrakeCLI` version 0.10.5 and the `--chapter-names` option worked perfectly for me. I see the chapters names as the video is being transcoded.

So I can't reproduce this.

**Comment by donmelton** [comment] 2016-11-13 04:04
@martinpickett I'm moving this issue from "bug" status to "help wanted" because I can't reproduce your problem. And, frankly, I'm at a loss to explain what's going wrong.

The only thing that looks slightly unusual with your inputs is your chapters file doesn't contain a line ending after the last chapter. Maybe HandBrake is barfing at that.

**Comment by martinpickett** [comment] 2016-11-13 10:51
Thank you for testing. Clearly something strange is happening on my system. I'll do some testing and update this thread if I find out what the problem is.

**Comment by donmelton** [comment] 2016-11-13 15:52
@martinpickett Thanks! I am very curious to get to the bottom of this.

**Comment by martinpickett** [comment] 2016-11-14 18:45
Well this is embarrassing, I can't replicate this issue. I've tried a bunch of different videos (including the one that failed the first time) and in each case the chapter names are added.  The only thing I did was to restart my computer. 

I'm sorry if this has caused any undue angst or worry and thank you for helping out.

**Comment by donmelton** [comment] 2016-11-14 20:20
@martinpickett No worries. I'm just happy it's all working now.

And I'm glad you opened the issue. Nothing wrong with helping someone verify. So don't be afraid to open issues like this again.

I'll close this now that it's resolved.

**Closed by donmelton** 2016-11-14 20:20 UTC
Labels: help wanted
