### ISSUE TITLE
multitiple files convert like query ?

### ISSUE THREAD

**Issue by senkron24** [donmelton/video_transcoding#174] opened 2017-10-25 20:49 UTC
big thx for this scripts
its a posible to start folder to transcode all files one to one with same name i try same variant bud i not get this sucess and the problem its thad the movie name will not same if you choose just folder the name of movie will the name of folder..
if its posible please need one example
kind regarts

**Comment by donmelton** [comment] 2017-10-25 22:01
@senkron24 I'm honestly not sure that I understand what you want to do. And for that I sincerely apologize because I know you're trying to write as clearly as possible. 

If you want to transcode multiple files in a folder with a single command you cannot pass a path to that folder as an argument. That's because folder arguments are interpreted as DVD or Blu-ray disc image directories.

However, you can do something like this:

```
transcode-video /path/to/Folder/*.mkv
```

... and your shell should expand the `*` to all the MKV files in that folder.

Or, you could simple use a batch script. Which is what I do. Here's how to do that:

https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video

I hope that helps.

**Comment by senkron24** [comment] 2017-10-29 12:42
ooo yes thad fine. exackly thad i mean with multi files with one comand
i will try this comand to do this
big thx for the help ..



Yasar Maymak

TvJoy Iptv Global Systems ..

Best Regarts
İyi Çalışmalar
---------------------
mail: yasar@tvjoy.tv
mail: senkron24@gmail.com

Tel: +905427885669



2017-10-26 1:01 GMT+03:00 Don Melton <notifications@github.com>:

**Comment by senkron24** [comment] 2017-10-29 14:30
i just test like this comand line 
root@tvjoy:/# transcode-video "/home/vip2/transc/*.avi" -o "/home/vip2/Finish"
bud get a result like this 
/usr/local/bin/transcode-video: No such file or directory - /home/vip2/transc/*.avi

No such file or directory bud thare its video files exist with avi format 

can help me to make its ..?

**Comment by donmelton** [comment] 2017-10-29 19:56
@senkron24 Sorry I took so long to reply.

The problem is that you're quoting the `*` in the input name as a literal string instead of allowing your shell to perform pathname expansion on it.

Try this instead:

```
transcode-video "/home/vip2/transc/"*.avi -o "/home/vip2/Finish"
```

Do you see the difference? Only the base pathname in the input is quoted. The `*.avi` is not.

I hope that helps.

**Comment by senkron24** [comment] 2017-10-31 09:58
no problem thank your for your nice support 
oo yeah i see the difrens and its works very great ,now all its ok 

Kind regarts

**Comment by donmelton** [comment] 2017-10-31 15:29
@senkron24 You are very welcome! I'm glad that worked.

I'll close this now but don't be afraid to open another issue if you run into a problem.

**Closed by donmelton** 2017-10-31 15:29 UTC
Labels: help wanted
