### ISSUE TITLE
transcode-video fails when using the --output option on my Windows configuration

### ISSUE THREAD

**Issue by Shentokk** [donmelton/video_transcoding#111] opened 2017-01-03 01:55 UTC
http://pastebin.com/Bcr3PufB

Whenever I use the output flag, I get an error code 3 from the script.

**Comment by donmelton** [comment] 2017-01-03 01:58
@Shentokk I don't understand what you were trying to do. Are you using `transcode-video` here? I need _much_ more context if I'm to provide help here. Thanks.

**Comment by donmelton** [comment] 2017-01-03 01:59
@Shentokk For example, please provide the steps you used to cause the problem and what you expected to happen instead.

**Comment by Shentokk** [comment] 2017-01-03 02:00
I apologize. This is the command I was using.

ruby transcode-video --force-rate 23.976 -H optimize --add-audio all --copy-audio all --add-subtitle all --force-subtitle 1 -H chapters=1-5 --output "Aa Bakudan.mkv" "disc1.mkv";

**Comment by donmelton** [comment] 2017-01-03 02:05
@Shentokk Thanks. No worries, problem reports are hard.

Did this command not transcode your movie? Otherwise I don't understand what the bug is?

BTW, you shouldn't need to prefix your command with `ruby`, even on Windows. If that's somehow required for you, then it's likely you have a `$PATH` configuration problem as well.

**Comment by Shentokk** [comment] 2017-01-03 02:06
I haven't been able to figure out how to fix the issue that requires me to use the ruby prefix. The command does not transcode the movie. It starts, then spits out the error 3 message and ends.

**Comment by donmelton** [comment] 2017-01-03 02:10
@Shentokk OK, what happens if you don't put a space in the output filename? Or, better yet, you don't use the `--output` command at all?

Also, which version of `transcode-video` are you using?

**Comment by Shentokk** [comment] 2017-01-03 02:14
I updated transcode-video this morning.
I get the same error when doing a file name without spaces.
I get error "transcode-video: output file exists: disc1.mkv" when leaving out the --output command.

**Comment by donmelton** [comment] 2017-01-03 02:18
@Shentokk OK, you updated. That's good. What  is the output of `transcode-video --version` then?

Change to a directory that doesn't contain your input file when you're not using the `--output` option. I need to know whether that works.

**Comment by Shentokk** [comment] 2017-01-03 02:20
transcode-video 0.13.0
Copyright (c) 2013-2017 Don Melton

I get the same error when using a different directory as well.

**Comment by Shentokk** [comment] 2017-01-03 02:21
transcode-video 0.13.0
Copyright (c) 2013-2017 Don Melton

It works fine without the --output option when I have the source file in a different directory.

**Comment by donmelton** [comment] 2017-01-03 02:31
@Shentokk Excellent! Then we have narrowed down the problem.

OK, looking at your original console output from pastebin, I see these lines:

```
[01:15:08]  * source
[01:15:08]    + disc1.mkv
```

```
[01:15:08]  * destination
[01:15:08]    + /home/Shentok/bin/disc01.mkv
```

It looks like your output filename is being ignored based on your input command. I've never seen this problem before on any platform.

Is the directory that contains your input file, "disc01.mkv," writable? In other words, can you create other files in that directory?

What happens if you just specify a output directory, i.e. not a file?

Also, what happens if you use the previously released version of `HandBrakeCLI`, preferably version 0.10.5?

**Comment by Shentokk** [comment] 2017-01-03 02:36
I can create other files in that directory. I just tested that with the cygwin `touch` command. I also get the same error when just using a directory for the `output` command.

**Comment by donmelton** [comment] 2017-01-03 02:38
@Shentokk OK, do you have an older version of `HandBrakeCLI` around to try the other test?

**Comment by Shentokk** [comment] 2017-01-03 02:38
I just tried 0.10.5 as you suggested and I get the same error.

**Comment by donmelton** [comment] 2017-01-03 02:48
@Shentokk Excellent! We have narrowed the problem even more. I love this kind of thing. :)

OK, since I know the `--output` option normally works on Windows, and I haven't changed anything in that code in over a year, there must be something in your runtime configuration that's causing the problem. The fact that you have to prefix command with `ruby` leads me to believe there's something screwy about your environment.

What can you tell me about your configuration that can help us narrow this further?

**Comment by Shentokk** [comment] 2017-01-03 02:51
I am using cygwin64 on Windows 10 Home. I haven't updated cygwin64 in about a year. I only installed necessary components to run `transcode-video`. I'm not sure what other kind of information I can provide to help.

**Comment by donmelton** [comment] 2017-01-03 02:52
@Shentokk What version of Ruby are you using and how did you install it?

**Comment by donmelton** [comment] 2017-01-03 02:57
@Shentokk BTW, which shell are you using when you invoke `transcode-video`? Bash or PowerShell or the Windows default?

**Comment by Shentokk** [comment] 2017-01-03 03:00
I am using Bash.
I am using version ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-cygwin] according to `ruby -v`.
I'm trying to recall how I installed Ruby, but I'm not sure as its been quite some time.

**Comment by donmelton** [comment] 2017-01-03 03:04
@Shentokk If you installed the `video_transcoding` Gem within Bash, is it listed when you invoke:

```
gem list
```

Also, what is the output of:

```
which transcode-video
```

**Comment by Shentokk** [comment] 2017-01-03 03:07
```
*** LOCAL GEMS ***

actionmailer (4.2.5.2)
actionpack (4.2.5.2)
actionview (4.2.5.2)
activejob (4.2.5.2)
activemodel (4.2.5.2)
activerecord (4.2.5.2)
activerecord-deprecated_finders (1.0.4)
activesupport (4.2.5.2)
arel (6.0.3)
atk (2.2.5)
bcrypt (3.1.10)
bigdecimal (1.2.7)
binding_of_caller (0.7.2)
builder (3.2.2)
bundler (1.9.9)
byebug (4.0.5)
cairo (1.14.1)
cairo-gobject (2.2.5)
celluloid (0.16.0)
clutter (2.2.5)
clutter-gtk (2.2.5)
coffee-rails (4.1.1)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
columnize (0.9.0)
curses (1.0.1)
debug_inspector (0.0.2)
erubis (2.7.0)
execjs (2.5.2)
gdk3 (2.2.5)
gdk_pixbuf2 (2.2.5)
gettext (3.1.4)
gio2 (2.2.5)
glib2 (2.2.5)
globalid (0.3.6)
gobject-introspection (2.2.5)
goocanvas (2.2.0, 1.2.6)
gstreamer (2.2.5, 1.2.6)
gtk2 (2.2.5)
gtk3 (2.2.5)
gtksourceview2 (2.2.5)
gtksourceview3 (2.2.5)
hike (1.2.3)
hitimes (1.2.2)
hoe (3.12.0)
hpricot (0.8.6)
htmlentities (4.3.2)
i18n (0.7.0)
imagesize (0.1.1)
io-console (0.4.2)
jbuilder (2.2.16)
journey (1.0.4)
jquery-rails (4.0.5)
json (1.8.2)
kgio (2.9.3)
listen (3.0.6)
locale (2.1.0)
loofah (2.0.3)
mail (2.6.3)
marc (0.7.1)
mime-types (2.6.2)
minitest (5.6.1, 5.4.3, 4.7.5)
molinillo (0.2.3)
multi_json (1.11.0)
mysql2 (0.3.18)
net-http-persistent (2.9.4)
nokogiri (1.6.7.2)
oj (2.12.8)
pango (2.2.5)
pg (0.18.2)
pkg-config (1.1.6)
polyglot (0.3.5)
poppler (2.2.5)
power_assert (0.2.2)
psych (2.0.13)
racc (1.4.12)
rack (1.6.4)
rack-cache (1.2)
rack-ssl (1.4.1)
rack-test (0.6.3)
rails (4.2.5.2)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
railties (4.2.5.2)
raindrops (0.13.0)
rake (10.4.2)
rake-compiler (0.9.3)
rdoc (4.2.0)
rsvg2 (2.2.5)
ruby-dbus (0.11.0)
rubygems-update (2.4.8)
sass (3.4.21)
sass-rails (5.0.4)
sdoc (0.4.1)
sprockets (3.4.1)
sprockets-rails (2.3.3)
sqlite3 (1.3.10)
syck (1.0.5)
test-unit (3.0.8, 2.5.5)
text (1.3.0)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
timers (4.0.1)
treetop (1.4.15)
turbolinks (2.5.2)
tzinfo (1.2.2)
uglifier (2.7.1)
unicorn (4.9.0)
video_transcoding (0.13.0, 0.2.7, 0.2.6)
vte (2.2.5)
vte3 (2.2.5)
web-console (2.3.0)
webkit-gtk2 (2.2.5)
yajl-ruby (1.2.1)
zoom (0.4.1)
```
```
which: no transcode-video in (/usr/local/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/Common Files/Microsoft Shared/Windows Live:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/adb:/cygdrive/d/Program Files (x86)/Smart Projects/IsoBuster:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/d/Program Files (x86)/GtkSharp/2.12/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Windows Phone TShell:/cygdrive/c/Program Files (x86)/Skype/Phone:/cygdrive/c/WINDOWS/system32/config/systemprofile/.dnx/bin:/cygdrive/c/Program Files/Microsoft DNX/Dnvm:/cygdrive/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/cygdrive/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/cygdrive/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/cygdrive/c/Program Files/Common Files/Microsoft Shared/Windows Live:/cygdrive/c/Users/Shentok/AppData/Local/Microsoft/WindowsApps:/usr/lib/lapack)
```

**Comment by donmelton** [comment] 2017-01-03 03:11
@Shentokk Well, the latest `video_transcoding` is there along several ancient versions. You need to execute this command right away:

```
gem cleanup
```

That will delete out of date Gems.

The bigger issue is that Bash can't find `transcode-video` in your `$PATH`. That's a serious problem and could very well be causing the bug you're seeing. I just don't know.

**Comment by Shentokk** [comment] 2017-01-03 03:13
I'd be willing to do a fresh install of cygwin if that would be the best course of action, though it would take some time.

**Comment by donmelton** [comment] 2017-01-03 03:30
@Shentokk Well, you should probably re-install Cygwin and Ruby anyway just to solve the `$PATH` problem. And at this point, I don't know what else to suggest.

**Comment by Shentokk** [comment] 2017-01-03 03:33
Okay, I'll do that. For now I'll just have my source files in a different directory since that seems to be a good workaround. Thank you so much for your time.

**Comment by donmelton** [comment] 2017-01-03 03:40
@Shentokk No problem! I was glad to do it, sir. I'll leave this open for now until I hear from you.

**Comment by Shentokk** [comment] 2017-01-03 04:21
I did a fresh install of cygwin and I still have the `$PATH` issue it seems. I haven't been able to turn up any information on how to fix that issue either.

**Comment by donmelton** [comment] 2017-01-03 04:29
@Shentokk Dang. Maybe the issue is with Ruby then?

You probably noticed I asked on Twitter if anyone else was having the same problem. I figured it was worth a shot.

**Comment by samhutchins** [comment] 2017-01-03 09:20
--output works fine for me. The main difference between our environments is probably Cygwin: I don't use it. I wrote up a short guide on installing these tools without using Cygwin, if that's of any interest to you: https://gist.github.com/samhutchins/3b06c3af60f5849ab825a6e5926efdc3

**Comment by donmelton** [comment] 2017-01-03 15:47
@samhutchins Thanks!

**Comment by donmelton** [comment] 2017-01-10 16:34
@Shentokk Any update on this? It's been over a week and I'm wondering whether we still need to hold this issue open?

**Comment by Shentokk** [comment] 2017-01-10 21:32
No update. You can close it if you want. I don't think I'd be able to find a solution on my own.

**Comment by donmelton** [comment] 2017-01-10 21:36
@Shentokk Ouch. OK, I'll leave it open for awhile longer in case someone else out there has a useful suggestion for you. But at the moment, I'm out of ideas because every other Windows user I've spoken with doesn't have this problem. Granted, that's not a lot of people, but still.

**Comment by samhutchins** [comment] 2017-01-10 21:43
@Shentokk is Cygwin a must have for you? If you follow the guide I posted earlier you can call transcode-video from CMD. I have no problems with the --output option on Windows 10, and the only obvious environment difference between us is Cygwin.

**Comment by JMoVS** [comment] 2017-01-18 11:01
@Shentokk Could you try supplying a full path that you know is writable in the --output command? I don't know much about cygwin but eg provide the full path instead of just the name?

**Comment by Shentokk** [comment] 2017-01-18 22:40
No luck. I just gave it a go and the same error is still produced.

**Comment by donmelton** [comment] 2017-01-30 06:57
@Shentokk Other than the suggestion to remove Cygwin and reinstall on Windows using one of the two methods now documented. I'm not sure how much further we can go to help here.

So, I'm closing this for now.

**Closed by donmelton** 2017-01-30 06:57 UTC
Labels: help wanted
