### ISSUE TITLE
[aac @ 0x17c8fe0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.

### ISSUE THREAD

**Issue by dgibbs64** [donmelton/video_transcoding#135] opened 2017-03-10 22:47 UTC
Hello Don. I have updated to the latest version however this has broken the converter for me. I think it may be related to a change you made in version 0.15.0

I am getting the following error

```
[aac @ 0x17c8fe0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
```

Its been working great until I have updated. My conversion server is running Ubuntu 16.04. Would you be able to re add to experimental option back in? or add an if statement adding it back for Ubuntu?

Let me know if you need any more info. Thank you

**Comment by donmelton** [comment] 2017-03-11 18:28
@dgibbs64 Sorry I took so long to respond. This is not a bug.

It's likely that your version of `ffmpeg` is too old so it's requiring that deprecated option. What version of `ffmpeg` are you running now?

**Comment by dgibbs64** [comment] 2017-03-11 21:56
```ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
```
Ideally as Ubuntu 16.04 LTS it is unlikely to get the update to remove the experimental warning having a check to identify a ffmpeg version older that X will still have the experimental option used.

**Comment by donmelton** [comment] 2017-03-11 22:35
@dgibbs64 That's an ancient version of `ffmpeg` and likely other things, like proper crop detection, won't work either, at least not correctly. You need version 3 or later.

You can find up to date packages for Ubuntu here:

https://launchpad.net/ubuntu/+source/ffmpeg

I won't restore the option for older versions of `ffmpeg` because the latest `ffmpeg` spews warnings about it. I'm damned if I do and damned if I don't. :)

**Comment by dgibbs64** [comment] 2017-03-11 22:44
Yes I get your point if 3.0 is way better. However as the current LTS version of Ubuntu does not have 3.0 its kind of an issue. The only way to go about this is updating to a non LTS version which I would rather avoid. 

If I remember correctly you use this mainly on mac? If possible it may be worth adding further installation notes for at least Ubuntu/debian. Also stating that ffmpeg 3.0 is only supported now.

Right dist upgrade for me. My conversion/transcode server has been great using your program and my automated bash script. I just drop the files in a directory and let them to go.

**Comment by donmelton** [comment] 2017-03-11 23:19
@dgibbs64 Yes, I use the tools mainly on my Mac. You make a good point about documentation. I described the `ffmpeg` version requirement when I made the change to `convert-video` in the feature proposal, but I didn't include it the "README" document other than in the change log. I'll figure out how to mention that.

I'm glad the tools are working out for you! But I'm sorry you hit this snag.

**Comment by dgibbs64** [comment] 2017-03-12 12:07
I have completed a dist upgrade now and its all working again :D. Thanks

**Comment by donmelton** [comment] 2017-03-12 15:23
@dgibbs64 Excellent! Sorry to have to put you through that. :)

OK, I'll close this then.

**Closed by donmelton** 2017-03-12 15:23 UTC
Labels: help wanted
