### ISSUE TITLE
HandBrakeCLI version detection fails

### ISSUE THREAD

**Issue by kvanh** [donmelton/video_transcoding#139] opened 2017-04-03 16:05 UTC
I think version output from the HandBrakeCLI nightly builds has changed and at least detect-crop says a different version is needed. i assume the transcoder reports same.

HandBrakeCLI nightly build downloaded 2017-04-03:
$ HandBrakeCLI --version
[11:01:49] hb_init: starting libhb thread
[11:01:49] thread 700003937000 started ("libhb")
HandBrake 20170329202521-9884aa1-master

HandBrake has exited.
$

HandBrakeCLI release version (1.0.3):
$ ./HandBrakeCLI --version
[11:02:49] hb_init: starting libhb thread
[11:02:49] thread 700008961000 started ("libhb")
HandBrake 1.0.3
$

looking at the version detection in lib/handbrake.rb it might be the extra line of "HandBrake has exited." causing the issue or the date based version earlier on. I really need to bone up on my ruby.

**Comment by kvanh** [comment] 2017-04-03 16:21
It's the HandBrake has exited causing the problem.  I changed the 2 regex's in lib/handbrake.rb to:
/^HandBrake (\d[^ ]+)/

so it would only grab the line with handbrake and a digit following it.  Seems to be working now.

**Comment by donmelton** [comment] 2017-04-03 18:10
@kvanh Thanks for filing this!

Yeah, I can confirm the bug. The problem is that the HandBrake development team changed the code to embed the new-style version number in the output of `--preset-list`, which was the only way you could get the version number in the old days. Unfortunately, I'm using the fact that the number is in the `--preset-list` output as a indicator that it's an old version.

So, your patch will fix the case of a failure with a nightly build, but it will likely break in other situations.

I'll come up with a fix for this later today when I return.

Thanks again!

**Comment by donmelton** [comment] 2017-04-03 21:10
@kvanh D'oh! I was completely wrong about the exact reason. You were right. The bug is caused by the extra "`HandBrake has exited.`" line at the end of the output.

And your fix will work, too. However I prefer changing those regex lines to "`/^HandBrake ([0-9][^ ]+)/`" for my own anal-retentive, consistency reasons. :)

**Comment by donmelton** [comment] 2017-04-03 21:15
@kvanh OK, it turns out a better fix is to change that regex line to "`/^HandBrake ([^h][^ ]+)/`" because some HandBrake versions in the past have actually begun with letters (e.g. "`svn`") but none of those letter appears to be a lowercase "`h`". Go figure.

**Comment by donmelton** [comment] 2017-04-03 21:28
@kvanh OK, I've tried just about every version of HandBrake I have lying around (which is quite a few of them, believe you me) and the  "`/^HandBrake ([^h][^ ]+)/`" fix seems to work in all cases. So I'm going with that. As soon as I can get another bug fix done, I'll release this. Probably tonight or tomorrow.

Thanks again!

**Comment by donmelton** [comment] 2017-04-04 01:54
@kvanh OK, the fix is in version 0.17.2. Just `gem update video_transcoding` and you'll have it.

Thanks again!

**Closed by donmelton** 2017-04-04 01:54 UTC
Labels: bug
