### ISSUE TITLE
mp4track failing for unknown reason

### ISSUE THREAD

**Issue by richard5mith** [donmelton/video_transcoding#78] opened 2016-08-09 21:10 UTC
I record timelapse of Lego builds in iStopMotion, which results in giant files because they are uncompressed full frame video. Once completed, I run them through transcode-video and normally don't have an issue. But this time round I'm getting an error.

```
transcode-video --quick --mp4 -vvv --no-audio bucketwheelbuild6.mov -o ~/Desktop/Bricks/
transcode-video 0.10.0
Copyright (c) 2013-2016 Don Melton
HandBrake 0.10.5 found...
HandBrake 0.10.5 found...
Processing: bucketwheelbuild6.mov...
Scanning media title 1 with HandBrakeCLI...
[21:51:55] hb_init: starting libhb thread
HandBrake 0.10.5 (2016021100) - Darwin x86_64 - https://handbrake.fr
8 CPUs detected
Opening bucketwheelbuild6.mov...
[21:51:55] CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
[21:51:55]  - Intel microarchitecture Haswell
[21:51:55]  - logical processor count: 8
[21:51:55] OpenCL device #1: Intel Iris Pro
[21:51:55]  - OpenCL version: 1.2 
[21:51:55]  - driver version: 1.2(Jun 30 2016 20:43:33)
[21:51:55]  - device type:    GPU
[21:51:55]  - supported:      YES
[21:51:55] OpenCL device #2: AMD AMD Radeon R9 M370X Compute Engine
[21:51:55]  - OpenCL version: 1.2 
[21:51:55]  - driver version: 1.2 (Jun 30 2016 20:50:27)
[21:51:55]  - device type:    GPU
[21:51:55]  - supported:      YES
[21:51:55] hb_scan: path=bucketwheelbuild6.mov, title_index=1
libbluray/bdnav/index_parse.c:162: indx_parse(): error opening bucketwheelbuild6.mov/BDMV/index.bdmv
libbluray/bdnav/index_parse.c:162: indx_parse(): error opening bucketwheelbuild6.mov/BDMV/BACKUP/index.bdmv
libbluray/bluray.c:2182: nav_get_title_list(bucketwheelbuild6.mov) failed
[21:51:55] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[21:51:55] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'bucketwheelbuild6.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2016-08-03 18:11:15
    encoder         : x iStopMotion
    encoder-zkn     : x iStopMotion
  Duration: 00:02:48.73, start: 0.000000, bitrate: 995343 kb/s
    Stream #0.0(eng): Video: rawvideo, argb, 1920x1080, 995328 kb/s, 1500 tbn (default)
    Metadata:
      creation_time   : 2016-08-03 18:11:15
    Stream #0.1(eng): Data: tmcd / 0x64636D74
    Metadata:
      creation_time   : 2016-08-05 19:04:25
[21:51:55] scan: decoding previews for title 1
[21:51:56] scan: 2 previews, 1920x1080, 15.000 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1
[21:51:56] libhb: scan thread found 1 valid title(s)
+ title 1:
  + stream: bucketwheelbuild6.mov
  + duration: 00:02:48
  + size: 1920x1080, pixel aspect: 1/1, display aspect: 1.78, 15.000 fps
  + autocrop: 0/0/0/0
  + support opencl: yes
  + support hwd: not built-in
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 00:02:48
  + audio tracks:
  + subtitle tracks:
HandBrake has exited.

Scanning with mp4track...
mp4track - MP4v2 2.0.0 found...
ERROR: unable to open for read: bucketwheelbuild6.mov
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
Warning (charLength > fixedLength) in src/mp4file_io.cpp at line 400
ReadProperties: atom 'raw ' is too small; overrun at property: compressorName (src/mp4atom.cpp,386)
/usr/local/bin/transcode-video: scanning failed
```

My guess is that since there's no audio, mp4track is failing. But since I'm specifying no-audio, why is mp4track being run?

**Comment by donmelton** [comment] 2016-09-15 05:04
@richard5mith Sorry I took so long to look at this in depth. I suck as a human being.

OK, specifying `--no-audio` only affects the output file. It has nothing really to do with the input.

The `mp4track` tool is used to scan MP4 media files and identify tracks and their attributes. It should work fine if there's no audio track. I suspect that issue is a red herring. So, there's must be something else wrong with this file.

Can you post the file somewhere online so I can examine it myself? Thanks.

**Comment by donmelton** [comment] 2016-09-15 05:13
@richard5mith I've just confirmed that `mp4track` and `transcode-video` work fine with `.mov` files with no audio tracks. So that's definitely not the issue here.

**Comment by richard5mith** [comment] 2016-09-15 08:33
Well I guess my guess was the wrong guess. :)

I'll see if I have any files left with the problem. I've been re-exporting them out of iStopMotion again using it's export option, and that then gives me a file that works, so I've then be deleting the originals. But I might have one left.

**Comment by donmelton** [comment] 2016-09-15 14:30
@richard5mith It was still a good guess. :)

**Comment by donmelton** [comment] 2016-09-15 20:56
@richard5mith Looking at your diagnostic output again, perhaps the problem is due to the `rawvideo` format of the video stream? I don't have sample files in that format so I can't be sure.

**Comment by richard5mith** [comment] 2016-09-18 20:42
I don't have any files left which give me the same error, because I haven't done any Lego videos this week. I tried to create a test file and it gives me an error when trying to convert, but it's a different error!

https://www.dropbox.com/s/isl3e9mij49jxon/test.mov?dl=0

**Comment by donmelton** [comment] 2016-09-18 20:57
@richard5mith Thanks for the file!

OK, the reason why both `transcode-video` and `convert-video` fail on that file is that `HandBrakeCLI` doesn't think it contains a title, i.e. a video track. You can simple try:

```
HandBrakeCLI --scan --input test.mov
```

... and watch `HandBrakeCLI` barf on it.

I think the reason is that the file contains RGB raw video. The good news is that FFmpeg seems to handle it. So I would suggest using that tool instead of a workflow with HandBrake.

**Comment by donmelton** [comment] 2016-09-26 15:46
@richard5mith As near as I can tell, there's not a "bug" in `transcode-video`, `mp4track` or `HandBrakeCLI` here. Perhaps a "limitation" in the underlying implementation of the latter two, but that's not something I can fix.

So, I'm closing this for now but if you still need help or suspect there really is a larger problem then comment here and I'll reopen the issue.

Thanks for reporting this!

**Closed by donmelton** 2016-09-26 15:46 UTC
Labels: help wanted
