### ISSUE TITLE
HEVC output is not playable by QuickTime on macOS 10.14.2

### ISSUE THREAD

**Issue by mattwaltbriggs** [donmelton/video_transcoding#273] opened 2019-03-11 17:01 UTC
Using `ffmpeg -i ./00023.MTS -c:v libx265 -crf 28 -c:a aac -b:a 128k -tag:v hvc1 23.mp4` I am unable to create a file that can be played back by QuickTime on 10.14. The output appears to be compatible with other applications however.

ffmpeg version 4.1.1 installed with homebrew
`configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr`
macOS 10.14.2
Quicktime 10.5 (928.50)

**Comment by donmelton** [comment] 2019-03-11 18:02
@mattwaltbriggs Sorry I took so long to respond. I was out walking the dog. ...

QuickTime is sure picky, isn't it? Dang. OK, I have to chauffeur my family around for an hour or two but when I get back I'll try this myself and see if I can figure out what's going on. Stay tuned...

**Comment by donmelton** [comment] 2019-03-11 21:33
@mattwaltbriggs OK, I just transcoded a different video (because I don't have "00023.MTS") with the same Homebrew-installed version of `ffmpeg` using your exact parameters... and "QuickTime Player" handled it fine. However, I am using macOS version 10.13.6, so maybe that's the difference?

**Comment by donmelton** [comment] 2019-03-11 21:35
@mattwaltbriggs BTW, have you opened an issue about this with the FFmpeg project yet? Because at this point, not being able to reproduce your problem, I'm not sure what else I can do.

**Comment by mattwaltbriggs** [comment] 2019-03-11 22:18
No, you won't have 00023.MTS 'cause it's a 10 GB video I need to transcode for work. :)
Unfortunately it happens for all videos transcoded with x265 with ffmpeg.
Maybe it is a MacOS 10.4.x issue.. Thanks for trying it anyway.
Will look into opening issue with FFmpeg project.

**Comment by donmelton** [comment] 2019-03-11 22:22
@mattwaltbriggs No worries! Sorry I couldn't solve the problem for you. And feel free to open other "general" video transcoding issues here. I don't mind.

Also, let me know if you find out anything about this from the FFmepg project. I'll close this now but feel free to comment here again. I get all the notifications.

Good luck!

**Closed by donmelton** 2019-03-11 22:22 UTC
Labels: help wanted
